### ISSUE TITLE
Ask people why they stopped tipping (i.e. do an exit survey)

### ISSUE THREAD

**Issue by greggles** [gratipay/gratipay.com#1310]
Right now people stop using gittip and there's no sense of why that happens.

It would be nice to know why.
- Step 1 is probably starting with some metrics on the average number of weeks that people tip and identifying "churn"
- Step 2 is writing the survey (see below)
- Step 3 is probably figuring out how to notify people of the survey - since these people no longer come to the site we can't put it as a call to action on the site so it will have to be via email (#89) or twitter (#646) or gh interruptions (#73)

Maybe these questions would be good:
- Why did you start tipping someone on Gittip?
- Did you know you've stopped tipping?
- Why did you stop tipping?
- Is there an improvement to Gittip that would make you start tipping again?
- Anything else? (free comment area)

From a logistic perspective, there are lots of free or low cost survey tools. I personally like https://webform.com but there are lots of other options (Survey Monkey, survey.io etc.).
##

**Comment by different2** [comment]
Hey I just found this because I was curious if it was possible to tip people in github. I realize this is 2 years old but you guys might get notifications.. Also you might still be looking for improvements.. Anyways I searched for it because I didn't want to search for a way to pay programmers. But I'm a noob programmer asking people I meet for help, and I think "wow great this guy solved my problem so quickly! I feel so stupid now but I am really thankful!" The issues I am having is I am poor, like most programmers or aspiring ones. So if you market it towards people who have problems they would like help with, especially noob programmers. Also figure out ways for people to pay "alternatively" that they can earn money with. Perhaps a "future payment thing" People have an unlimited amount of coins. Coins are worth money, they vow to pay this person in the future so many coins for their help.

**Comment by whit537** [comment]
Glad you found us, @different2! You're discovering us at an interesting time. We've recently revamped our model significantly. Probably the best place to catch up with our current status is this [Gratipay 2.0](https://medium.com/gratipay-blog/gratipay-2-0-2453d3c53077) post.

**Comment by mattbk** [comment]
In light of Gratipay 2.0, I think this should take a backseat to getting everything working again, but this is definitely a +1 from me for data mining.

**Comment by webmaven** [comment]
@mattbk:
> In light of Gratipay 2.0, I think this should take a backseat to getting everything working again, but this is definitely a +1 from me for data mining.

I agree, but that day is creeping closer. We will need to determine at some point to what extent the 'gittip crisis' *directly* affected users leaving, and to what extent the subsequent loss of critical mass caused users to leave as a second order effect.

Those answers should inform how cautious we are about enforcing 'brand alignment' in cases like 'sexy-bash-prompt'.

**Comment by mattbk** [comment]
I read your response on the application and I suppose I understand.

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃
