### ISSUE TITLE
Gittip Fraud HOWTO

### ISSUE THREAD

**Issue by pjf** [gratipay/gratipay.com#2125]
Gittip involves moving money between people, and as such it's also a potential vehicle for fraud and money laundering. A typical workflow may be as follows:

* EvilPerson steals credit card details and attaches them to a gittip account.
* EvilPerson pays money to other Gittip accounts under their control.
* EvilPerson withdraws money from those other accounts, possibly via BitCoin, which—like its legally dubious cousin "cash"—is used by drug-lords, arms-dealers, and Portland street-food vendors.

Where this sucks for GitTip is when the fraud is discovered and the fraudulent credit-card pay-ins are reversed, leaving GitTip with the bill for the fraudulent pay-outs.

It would be useful to have a discussion as to how to combat this. New accounts giving lots of money to other new accounts are a potential sign of fraud, but an attacker may choose a less obvious (and less efficient) route to try and avoid detection.

One possible solution would be to have the concept of "cleared funds" and "uncleared funds". Pay-ins that can't be reverted (eg: Bitcoin) are automatically cleared. Those which *can* be reverted as 'uncleared' for a period of time, to at least increase the likelihood of us receiving fraud alerts before we pay-out of those funds.  Another solution would be some sort of fraud insurance.

Other suggestions and discussions very welcome here. Understanding potential attack patterns can help us defend against them when they arrive.

~ pjf

**Comment by whit537** [comment]
Finally circling back around to this one after an eventful couple of years. Gittip is now Gratipay, and Gratipay now has a well-established [policy](http://inside.gratipay.com/howto/support-users) for managing the private/public boundary in user support:

> **Protecting User Privacy**
>
1. Before answering questions or performing actions related to an account, verify the user's identity by asking for, "the first eight digits of the API key on your [Gratipay settings page](https://gratipay.com/about/me/settings/)." We generally don't trust even verified email addresses as identity confirmation (because of the risk of spoofing).
1. Never share personally identifying information about a user on GitHub or anywhere else without their explicit consent.
1. Copying anonymized, generic comments into a public GitHub ticket is okay, and so is a simple "+1" with a link to Freshdesk.

That was actually a sidebar in this ticket. The main point here was how to combat fraud, for which we've also adopted [policies](http://inside.gratipay.com/howto/review-accounts) by now.
