### ISSUE TITLE
tip note

### ISSUE THREAD

**Issue by bekishore** [gratipay/gratipay.com#222]
I would like to remember why i started gittip-ing and increased... etc 

Please provide a public and private note against each person I gittip...
##

**Comment by whit537** [comment]
+1 https://gratipay.freshdesk.com/helpdesk/tickets/1705

> Also, a short description next to individual names, i.e. “webmaster”, “forum moderator”, “gratipay founder”, etc.

**Comment by schlick** [comment]
+1 the ability to record a note as to why I am tipping a person would be great. Preferably a private note as it's mostly just a reference for myself. Some people I tip because of an obscure plugin they made and a year later I can't figure it out from their username/profile alone.

**Comment by whit537** [comment]
Thanks @schlick. FYI it's likely that this ticket will become obsolete in the next couple months, due to changes we'll be making in light of Balanced shutting down. tl;dr We'll probably be evolving Gratipay to focus on giving to specific open-source projects. Deep dive here if you like:

https://medium.com/gratipay-blog/balancedshutdown-3a9fdb32e9c6
https://github.com/gratipay/inside.gratipay.com/issues/180

**Comment by whit537** [comment]
I mean, the same thing happens to me. I go look at my Giving page and I scratch my head and wonder, "Who is this person, again?" :)

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃
