### ISSUE TITLE
play nice with charities

### ISSUE THREAD

**Issue by chadwhitacre** [gratipay/gratipay.com#249]
This is related to project tips (#27) but deserves its own thread. Say a charity like @saxifrage or @watsi or @python wants to accept funds via ~~Gittip~~ Gratipay. They have charity status so they can offer a tax advantage to donors. Can ~~Gittip~~ Gratipay support this somehow? A related idea is to make ~~Gittip~~ Gratipay itself a charity (#101).
##

**Comment by whit537** [comment]
From Neal Gorenflo at [Shareable](http://www.shareable.net/):

> On donations, we're fiscally sponsored by Tides Center and we can only accept donations through approved channels (like NetworkforGood).  Unfortunately, we can't take donations through Gratipay.  We may seek independent 501c3 status in 2015, and it will likely work if / when we get that status.

But see also [Twitter](https://twitter.com/Shareable/status/552232977934336000). :dancer: For context: I've been emailing with Neal a little bit and made a small (personal) donation to Shareable using NetworkforGood after his above response.

**Comment by timothyfcook** [comment]
Still want this. "Give to the people, teams, and projects building the world you want."

**Comment by mattbk** [comment]
> Specifically, we need:
> - a way for organizations to provide receipts to their supporters (this could be automatic via e-mail on a monthly basis and could let donors remain anonymous).

Doesn't sound hard? Part of https://github.com/gratipay/gratipay.com/issues/1199.
> - a way to ask for supporter's permission to provide contact info/names to the organization

Falls under https://github.com/gratipay/gratipay.com/issues/236? Could be done in aggregate in order to maintain anonymity (only if n >10, for example).
> - probably an API integration to allow the organization to migrate giving/contact info into Salesforce/Mailchimp, etc. or at least export to .csv

Sounds like this could be packed into the point above.

Is there any legal difficulty in collecting payments on behalf of a charity and maintaining tax-deductible status? I feel like this just came up somewhere.

**Comment by hashar** [comment]
@whit537 I am very sorry it did not work out.  But there is one sure thing: at least you tried to push your idea as far as you could.  Courage is sometime accepting the evidences.   I have been lurking at your initiative since the start probably, and I am quite impressed it went that far.

I have no doubt your next adventure will be a great one 🥇
