### ISSUE TITLE
My card has started to and keeps failing...

### ISSUE THREAD

**Issue by dmitshur** [gratipay/gratipay.com#2623]
[Took the convo private: https://gittip.freshdesk.com/helpdesk/tickets/729 &mdash;@whit537]

**Comment by shurcooL** [comment]
An update here (since that freshdesk isn't working).

I don't think my original debit card ever started working despite all the efforts here. I eventually removed it because I was getting a new credit card and I figured I would just use that instead.

I've added the new credit card today, and we'll see how well that works.

At the same time, I've decided to take a break/vacation from participating in Gratipay (including removing myself from the Gratipay team). I feel the cognitive overhead of using/having it, combined with problem above, has added stress and I'm not feeling good about it. I will reevaluate my use of it and role here with time and may or may not become more active again in the future. Thank you for all the effort in this difficult but worthwhile cause; it's not an easy journey.

**Comment by whit537** [comment]
Thanks for the follow-up @shurcooL, and for all of your support for Gratipay so far. I'm sorry that we haven't been able to make it work more smoothly for you. :-(

Ta ta for now and best wishes! :-)

**Comment by shurcooL** [comment]
Woohoo, at least the new credit card works.

**Comment by whit537** [comment]
Huzzah! :dancer:
