### ISSUE TITLE
add language selector to UI

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#2896]
Right now we depend on underlying browser configuration to pick a language. We should offer a language selector (little flags?) in the UI so users can easily override their browser default.

Suggested by @ptillemans in [IRC](https://botbot.me/freenode/gratipay/2014-11-05/?msg=24885282&page=1).
##

**Comment by whit537** [comment]
+1 from @revi on #3411:

> Currently gratipay (seems to) get user's language information and show that language's translation automatically, but I want to use English only (not translated one), but I cannot find any option for language on settings.

**Comment by revi** [comment]
>I'd either use a list with ISO language codes or a list of language names in the language itself, such as the one Wikipedia uses. Or maybe both, mixed together.

Maybe use [CLDR](http://enwp.org/CLDR)?

**Comment by jeanleonino** [comment]
It is still a problem. Since in my language it is half translated and I want to use it only in English, makes it _hard_ to use.

**Comment by FichteFoll** [comment]
+1

I hate half-translated languages and would prefer using English anyway because I fear loss of information during the translation which I could easily circumvent by just reading the original in English. There is, for example, a string that I can't properly interpret and have the strong feeling it was translated wrongly, but I can't even check that because without changing browser settings. Actually, I just did that so the problem will hopefully be going away. And yes, the translation is wrong.

**Comment by whit537** [comment]
> And yes, the translation is wrong.

@FichteFoll Care to [submit a fix](https://www.transifex.com/gratipay/gratipay/)? :)

**Comment by FichteFoll** [comment]
Thanks for the pointer, I think I did this right: https://www.transifex.com/gratipay/gratipay/translate/#de/core/35897103

**Comment by whit537** [comment]
I've accepted your suggestion on Transifex and made a new release. Can you confirm whether the translation is fixed?

**Comment by FichteFoll** [comment]
Confirmed. :+1:

**Comment by whit537** [comment]
Cool, thanks for the contribution! :-)

**Comment by whit537** [comment]
+1 [on Twitter](https://twitter.com/paglia_s/status/710541362194735105).
