### ISSUE TITLE
"report user" button

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3060]
Implement an on-site mechanism to report users for [terms](https://gratipay.com/about/terms/) violations. Currently [generic contact channels](https://gratipay.com/about/contact) are the only option.
##

**Comment by benhc123** [comment]
A form?

**Comment by colindean** [comment]
Yeah. Got the idea from how Facebook does it. It could eventually be modal on the userpage and/or have multiple screens, but something flat is fine for now.

I'm getting this error when I submit the form:

```
Traceback (most recent call last):
  File "/Users/colin/Source/gratipay/gratipay.com/env/lib/python2.7/site-packages/algorithm.py", line 288, in run
    new_state = function(**deps.as_kwargs)
  File "/Users/colin/Source/gratipay/gratipay.com/env/lib/python2.7/site-packages/aspen/algorithms/website.py", line 141, in delegate_error_to_simplate
    response = resource.respond(request, dispatch_result, response)
  File "/Users/colin/Source/gratipay/gratipay.com/env/lib/python2.7/site-packages/aspen/resources/simplate.py", line 65, in respond
    response = self.get_response(context)
  File "/Users/colin/Source/gratipay/gratipay.com/env/lib/python2.7/site-packages/aspen/resources/simplate.py", line 219, in get_response
    response.body = render(context)
  File "/Users/colin/Source/gratipay/gratipay.com/env/lib/python2.7/site-packages/aspen/renderers/__init__.py", line 103, in __call__
    return self.render_content(context)
  File "/Users/colin/Source/gratipay/gratipay.com/env/lib/python2.7/site-packages/aspen_jinja2_renderer.py", line 66, in render_content
    return self.compiled.render(context).encode(charset)
  File "/Users/colin/Source/gratipay/gratipay.com/env/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/colin/Source/gratipay/gratipay.com/env/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/colin/Source/gratipay/gratipay.com/error.spt", line 1, in top-level template code
    from __future__ import absolute_import, division, print_function, unicode_literals
  File "/Users/colin/Source/gratipay/gratipay.com/templates/base.html", line 46, in top-level template code
    <a href='/about/charts.html'>{{ _("{0} users exchanging {1} per week",
UndefinedError: 'format_number' is undefined
```

I'm using `on/%platform/redirect.spt` as inspiration...

**Comment by seanlinsley** [comment]
@colindean is that reproducible on what's currently been pushed to the `gh3060-add-report-button` branch?

**Comment by colindean** [comment]
@seanlinsley yes.

**Comment by whit537** [comment]
+1 https://twitter.com/WismerTrashCry/status/557594697716498432

**Comment by wismer** [comment]
Thanks for being quick to get back to me. The user in question is [infinitechan](https://gratipay.com/infinitechan/) - this user has been discussed before in [#118](https://github.com/gratipay/inside.gratipay.com/issues/118). To add to the reports of child abuse, and "doxxing" of people, there recently has been [several "SWAT"ing attempts](http://www.theguardian.com/technology/2015/jan/13/gamergate-hits-new-low-with-attempts-to-send-swat-teams-to-critics) being made against 8chan's critics, all organized by some users of the site. SWATing, as you might imagine, allows for the possibility of injury/death of the one being "pranked". 

I understand the desire that gratipay wants to avoid being heavy-handed in curating its user base, but I think this is an edge case worth considering.

**Comment by whit537** [comment]
Should we expand this to a "block user" implementation, or ticket that separately? If here, then reticketing from https://github.com/gratipay/gratipay.com/pull/3112#issuecomment-71927356 the idea that blocking a user would not only prevent them from giving to you, but would also prevent anyone who gives to them from also giving to you.

**Comment by colindean** [comment]
I'm not convinced of the value of blocking someone from giving you money, especially if the gift is anonymous.

I can see some people finding out and being disgusted that they were receiving money from someone they don't like, but I guess my take on it is a little different: I'd rather that someone I don't like give me their money, so that they can't spend it doing things I don't like.

I *do* see value in preventing people *downstream* from you from giving to people you've disallowed. That is, if Alice doesn't like Mallory, then Bob cannot give to Mallory without refusing a gift from Alice. I'm not sure how we could handle that without potentially de-anonymizing donors: Bob could crawl Gratipay to find out what everyone is giving/receiving, refuse the gift from Alice, and immediately crawl again to see whose giving/receiving changed, thereby possibly unmasking the relationship (or lack thereof) between Alice and Mallory.

However, preventing people downstream gets rid of the "no string attached" goal of Gratipay. Alice would be giving to Bob with a string attached: Bob cannot give to Mallory without refusing Alice's gift. Allowing this would be compromising on that mission, methinks.

I guess if we want to maximize user financial freedom, then we probably should give them the ability to refuse gifts once de-anonymized or via the "block user" feature, but I think that would belong in a separate ticket. This ticket should remain solely for user behavior reporting.

**Comment by whit537** [comment]
Block user reticketed as https://github.com/gratipay/gratipay.com/issues/3179.

**Comment by whit537** [comment]
+1 from @techtonik on https://github.com/gratipay/inside.gratipay.com/issues/375.
