### ISSUE TITLE
Charges higher than total gifts

### ISSUE THREAD

**Issue by seanlinsley** [gratipay/gratipay.com#3070]
For the past three weeks our charges have been about a thousand dollars higher than total gifts.

![screen shot 2015-01-07 at 11 37 20 am](https://cloud.githubusercontent.com/assets/688886/5649147/b16bd278-9661-11e4-8f29-09976884bf8a.png)

**Comment by seanlinsley** [comment]
The timing of #2914 suggests that it may be part of this.

**Comment by rohitpaulk** [comment]
I don't see anything wrong, guess it's just a lot of new people who are being upcharged $10 the first time round. 

The trend is very clear though, which makes me doubt whether I've missed something. Since 2012-11-29, these are the only paydays in which `charge_volume` has exceeded `transfer_volume`.

I'd like @Changaco to review this before we close.

**Comment by Changaco** [comment]
We're not actually charging more, `charge_volume` has simply been thrown off by #3011.
