### ISSUE TITLE
Communities can be spammed

### ISSUE THREAD

**Issue by benhc123** [gratipay/gratipay.com#3114]
I just noticed that someone can create a community, leave it, and it still appears in the search results for communities. This could potentially be used in a pretty-weak DOS (Denial-of-Search (Yes, I did just coin that phrase!) ) attack.

A malicious user could just create bulk communities and spam search results.

A pretty weak problem I know, but just thought I should mention it!

**Comment by whit537** [comment]
I don't like `DELETE`ing from the `communities` table, which is designed to be `INSERT`-only. Is there a reason we can't just use `current_community_members` instead of `communities` at https://github.com/gratipay/gratipay.com/blob/1775/www/search.spt#L65-L70, perhaps because of full-text indexing limitations on a view?
