### ISSUE TITLE
downgrade communities to tags

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3127]
@wilkie on [Twitter](https://twitter.com/wilkieii/status/557594476563398656):

> I don't think @Gratipay can ever say they're for supporting worthwhile communities when the biggest receiver is 8chan 

![b7z5oifiaaaaju4](https://cloud.githubusercontent.com/assets/134455/5822525/e084fd8c-a0a2-11e4-830a-6ee4724b5d02.png)

I agree. For communities on Gratipay to be meaningful, they need to be curated. I've been thinking that we should partner with relevant organizations to curate each of the communities we have. So the [OSI](http://opensource.org/) would curate the "open source" community, jQuery Foundation -> jQuery, PSF -> Python, etc.

What should we do if we can't find a partner? Should we simply turn off communities that are large enough to matter but for which we can't find curators? Should we leave them as-is but clearly mark them as "uncurated"?

**Comment by whit537** [comment]
[IRC](https://botbot.me/freenode/gratipay/2015-01-20/?msg=30040612&page=1)

**Comment by whit537** [comment]
I had thought that "open source" might be a trademark owned by OSI, but that's not obvious to me from skimming [their trademark guidelines](http://opensource.org/trademark-guidelines).

**Comment by whit537** [comment]
Nor from http://en.wikipedia.org/wiki/Open_source.

**Comment by colindean** [comment]
I think there's room for three kinds of communities: sponsored communities, moderated communities, and open communities. Sponsored and moderated communities have some gatekeeper, while open communities have no gatekeeper and are meant for ideas, concepts, or technologies that have no centralized body that can authoritatively act as a gatekeeper. 

Sponsored communities can be pushed by a company or organization wanting to recognize volunteers, without having to maintain a team account and deal with the politics of distributing team take. Gratipay can, perhaps for full consideration, put a logo on the sponsored community page and Gratipay says that people can ask to join the community or only be invited.

I do like the idea of effecting that anyone can join open communities, and that they are unmoderated and Gratipay isn't responsible for the membership of those communities.

Maybe another kind of community is a private community. Only people within that community can see who else is a member thereof, and the community can be visible or invisible on Gratipay. Not sure how this would work in Gratipay's goal of keeping as much transparent/public as possible, though.

**Comment by Changaco** [comment]
I suggest renaming communities to "tags" and limiting the number of tags per user.

**Comment by rummik** [comment]
I think we should model our communities after the way Google+ handles them.  Allow for communities with the same name by mapping them to `/community/115078169539467279272`, (replace `115078169539467279272` with a random ID), and let people create and moderate the communities as they see fit.  Give them to option to allow anyone to join, or require a review.  And give them the tools to ban people from a community.

We can then let people create new communities to replace them, since otherwise we have to play the risky game of handing what's effectively a community account to the right person.  People will join the communities they feel represent them best, even with multiple communities using the same name.

> I suggest renaming communities to "tags" and limiting the number of tags per user.

I originally felt like we should just nuke the current communities, but this effectively accomplishes the same goal.  We maybe shouldn't limit the number of tags though.

**Comment by whit537** [comment]
> I originally felt like we should just nuke the current communities

That'd be pretty easy to do.

**Comment by colindean** [comment]
I feel like nuking the communities is too easy and makes changes to a user account that a user might find disorienting. Maybe migrate existing communities to the new community structure, and then retire the old communities.

**Comment by rummik** [comment]
@colindean I'd be in agreement with that, but the question is, who would manage the migrated communities?  Also, I like @Changaco's thought of moving communities to tags, since it preserves the way they're being used currently anyway (do our communities really look like communities, or a bunch of tags that have user listings?)

**Comment by benhc123** [comment]
+1 for big communities.

**Comment by mattbk** [comment]
whit537: "For communities on Gratipay to be meaningful, they need to be curated."

I would change that to "worthwhile," since that's what the criticism is about.  The communities may or may not be meaningful at present--it's hard for me as a user to know what to do with them unless I want to search for likeminded people who I can tip.  Not sure if this would change at all if they were revamped.

If you want to keep communities, I think rummik's idea is best, with the addition that you would reserve certain names for use by Gratipay itself (to allow staff to curate "best of" and other exemplary users/organizations).

**Comment by seanlinsley** [comment]
Just a note here that the second-highest receiver in that screenshot saw this ticket, and is now considering leaving Gratipay for Patreon. This is what happens when you underwrite abuse.

https://twitter.com/LynnMagic/status/562669600479793152

Obviously my point belongs on a different ticket, but for historical context I thought it'd be good to point out when exactly it is that we lose users.

**Comment by mattbk** [comment]
FWIW, this is the stuff you need to have on the front page if you want to compete with Patreon: http://inside.gratipay.com/howto/behave-well

That being said, if Gratipay doesn't think 8chan is a good user, can't they just be banned?  http://inside.gratipay.com/howto/deal-with-bad-behavior

**Comment by techtonik** [comment]
How does Reddit manage it?

There could be an way to just hide the dark side of the human nature or the Internet, just make it an opt-in feature. Like many sites do with content not safe for work, the same could be done for no safe for biased public. Because banning someone needs a lot of dedication and it is rarely the case when there is only a single truth. "He who fights with monsters should look to it that he himself does not become a monster."

**Comment by whit537** [comment]
> I suggest renaming communities to "tags" and limiting the number of tags per user.
> I like @Changaco's thought of moving communities to tags

+1 for downgrading communities to tags. I've renamed this ticket to be about that. Maybe in the future we can think about implementing a new communities feature with proper moderation from the get-go.

**Comment by whit537** [comment]
Are we still interested in this, post-2.0?

cc: @mattbk

**Comment by mattbk** [comment]
Since all teams need to be reviewed first, it may not be necessary, because that seems to have been a major reason for this idea.  The "curating" is happening when a team is created.  

You could argue that if ~users aren't curated and we show "top givers" in a community (https://github.com/gratipay/gratipay.com/issues/3633), someone like 8chan could show up there--but giving is giving.

Especially regarding https://github.com/gratipay/gratipay.com/pull/3281#issuecomment-85618868, it will be a transition for current users.  I could be convinced either way, though.

**Comment by mattbk** [comment]
Edited my previous comment to clarify a bit.

**New Members**
This should probably show new teams (see below).

**Teams (Top Teceivers)**
Post 2.0, the purpose of communities is (should be?) to help ~users find teams to give to, based on subject matter.  Right now, http://gratipay.com/explore/teams is a list of team names and owners, with no (self or imposed) categorization.

**~users (Top Givers)**
However, we also want to recognize those ~users who are giving to a certain community.  We could do this in two ways:
- count the money going from each ~user going to teams in each category/with each tag, and display that giving amount on the community/tag page
- continue to allow ~users to join communities/tags, and use their total giving amount on the community/tag page

The first seems more accurate (and less subject to abuse), the second seems easier to implement.

**Comment by mattbk** [comment]
Considering this concept with respect to potential givers at https://github.com/gratipay/inside.gratipay.com/issues/319#issuecomment-154719150.  

Grouping teams and/or ~users by tag allows a potential giver to see who else is already giving.  It sounds a whole lot like 1.0 Communities in my head, except that a ~user belongs to a community that contains teams with a certain tag, _or_ because that ~user receives from a team with that tag.

Team A is tagged Python, PHP
Team B is tagged SQL, MySQL
Alice receives from Team A.
Bob receives from Team B.
Chad gives to Team A and Team B.
Donna gives to Team A.

Alice is part of Python and PHP.
Bob is part of SQL, MySQL.
Chad is part of Python, PHP, SQL and MySQL.
Donna is part of Python and PHP.
etc.

**Comment by mattbk** [comment]
+1 from https://github.com/gratipay/inside.gratipay.com/issues/483#issue-129209234

**Comment by mattbk** [comment]
PR where communities were turned off: https://github.com/gratipay/gratipay.com/pull/3706/files

Ideally we could modify these pieces back into a tag system.

**Comment by whit537** [comment]
Closing. We're far enough out from having had communities that we may as well start fresh.
