### ISSUE TITLE
redesign

### ISSUE THREAD

**Issue by arcfide** [gratipay/gratipay.com#3248]
The design language of the site is dated and lacks confidence building features. Especially the use of faded textures that don't integrate well and inconsistent typography, makes the whole site feel more like a gimmick and less like a site that is quality and well-established. The colors give a muddy feeling and sap strength from the site's overall language. 

The combination of serif fonts (possibly defaults) in main body text together with the wood give an "old" feeling to the site which rather than lending credibility, instead contribute to a feeling of being worn down. 

There's also a lack of clarity in the message across the site. It's difficult to determine the salient points about the site and "get" the site quickly and easily. 

All in all, it's lacking in streamlining and overall has a dated feel to it that should be updated.

**Comment by whit537** [comment]
Thanks for the feedback, @arcfide. We've struggled to recruit and retain visual designers, and could definitely use some help. Here's some blog posts documenting our design history, to bring you up to speed:

 - January, 2013: [Design Gittip](http://blog.gittip.com/post/41348666944/design-gittip/)
 - February, 2013: [New Design, New Team](http://blog.gittip.com/post/42849911683/new-design-new-team/)
 - May, 2014: [Breathing with Both Lungs](https://medium.com/inside-gratipay/breathing-with-both-lungs-c05e82bb1e69)

After that last post, we had a flurry of activity over on the [Inside Gratipay repo](https://github.com/gratipay/inside.gratipay.com/issues):

https://github.com/gratipay/inside.gratipay.com/issues/5
https://github.com/gratipay/inside.gratipay.com/issues/6
https://github.com/gratipay/inside.gratipay.com/issues/7
https://github.com/gratipay/inside.gratipay.com/issues/8
https://github.com/gratipay/inside.gratipay.com/issues/9
https://github.com/gratipay/inside.gratipay.com/issues/10
https://github.com/gratipay/inside.gratipay.com/issues/11
https://github.com/gratipay/inside.gratipay.com/issues/12
https://github.com/gratipay/inside.gratipay.com/issues/13

Until we find a visual designer that's willing to join the team full-time (unlikely, since we're bootstrapped), I expect we'll keep chipping away at this problem slowly, with efforts such as #2938, #3063, and #3220.

One challenge is the relationship between the sort of big-picture thinking required to design the product holistically, and our need to process work in small PRs due to tight time constraints. What would you recommend for next steps?

**Comment by mattbk** [comment]
> There's also a lack of clarity in the message across the site. It's difficult to determine the salient points about the site and "get" the site quickly and easily.

I think this is more immediately important than cleaning up all the design of the internal pages (and there are a lot of internal pages, if you get off the beaten path).  The front page needs to be compelling, and it's just not at the moment.  I thought there were more issues about that recently but I can't find them.

**Comment by arcfide** [comment]
I'd like to help in this at some point. Unfortunately, I'm swamped with other things at the moment. However, here are a few things that I think would help.

1. Is there a page collating all of the relevant information necessary for someone to implement a redesign?

2. If we're using the "Natural Planning Model" (which I like for this sort of stuff), then it needs to have on said page the following: 

    1. Purpose, 
    2. Vision, 
    3. Ideas, 
    4. Structure; 

  And, they should appear in that order. Namely, the page should start with the purpose of the site and the redesign. It should then include a vision of what such a thing should look like (a "perfect" outcome), possibly in terms of what the user would feel/see coming to the site. And then it should have a ton of ideas. They don't have to be good ideas, they just have to be ideas. In fact, at this stage, the less judgment made about the ideas the better. 

3. If a page can be created with that, then it's possible to begin a structured and careful redesign of the site with appropriate priorities. 

4. The Ideas should include the following points:

    1. What is the message of Gratipay? Why does someone care?
    2. What features does the site currently provide in all its nooks and cranies as well as the main front facing pages.
    3. What emotions and feelings do should a person feel while at the sight?
    4. What are the visual sensations (in terms of motion, color, shape, &c.) that we consider "positive" or desirable for one reason or another?
    5. What is the current site map and layout structure? 
    6. What are the current workflows and path ways through the website?
    7. What are the current design use cases?
    8. Links to existing user studies and other issues on the design of the site
    9. Site statistics on the most visited and least visited pages and a perhaps a Markov model on the distribution of visitation paths through the site.

5. Eventually after this information is collected and analyzed, the real issues with the site can emerge as well as priorities in a spectrum. That will lead to a specific structure for an action plan that will allow the site to move from where it is right now to its "ideal" state. 

The action plan may well involve clarifying the message early on the main page, and I think that's probably important even in the short term, but I'm not "involved" enough with Gratipay to determine how many of these issues have already been dealt with and what has already been done in this area. Also, I'm not a professional designer. I'm a Computer Scientist, and HCI/d (Human Computer Interaction and Design) is just a minor of mine. Whether that makes me qualified to help or not I don't know. 

One thing I would caution against is having a clean up that results in some pages having the old look and some the new. That can destroy confidence just as much. 

I hope that helps a little. I'm sure that much of this has probably already been considered on some level, and I have not dug into the whole set of repositories to find out what is and is not already there. That's why I think a single page would be helpful in this.

**Comment by whit537** [comment]
Thanks for the input, @arcfide.

> Is there a page collating all of the relevant information necessary for someone to implement a redesign?

I'm working on turning http://inside.gratipay.com/big-picture/product into that document, using #3220 as my scratch pad.

**Comment by whit537** [comment]
> Gratipay fucking sucks. Can I just write you a personal check? This is the hugest pain in the fucking ase.

http://www.funnyjunk.com/Literal+thumbwhoring+for+fj/funny-gifs/5503073/110#110

**Comment by whit537** [comment]
From https://github.com/gratipay/gratipay.com/pull/3694#issuecomment-133052743:

> Another thought: Teams are in between. On the one hand a Team page should appeal to ~users who want to give payments to the Team, and on the other to ~users who want to do work and take payroll. Out of scope for this PR but something to keep in mind when we're able to circle back around to #3248.

**Comment by whit537** [comment]
@arcfide We've got a revised visual design as of #3718. Could you review? Do you think it's enough to close this ticket?

https://gratipay.com/

**Comment by arcfide** [comment]
I think the redesign of the visuals of #3718 seems to be a reasonable effort and I think it's a great start. I certainly think that it's enough to close this ticket. Further improvements can be considered in other ways and other issues.

**Comment by whit537** [comment]
Thanks @arcfide. :-)
