### ISSUE TITLE
intermittent bad cert in the chain

### ISSUE THREAD

**Issue by clone1018** [gratipay/gratipay.com#3278]
![image](https://cloud.githubusercontent.com/assets/226638/6783075/dc74a2e6-d145-11e4-9f9c-3cf3af51c1b3.png)

**Comment by whit537** [comment]
Where are you seeing this, @clone1018? In Chrome I have the "does not have public audit records" message if I drill down, but the address bar is still locked green. Opera is green. Firefox is locked gray.

**Comment by clone1018** [comment]
Version 42.0.2311.39 beta (64-bit)

Which should be the next stable.

**Comment by whit537** [comment]
@clone1018 Are you sure the warning you're seeing is due to the audit records issue? That was also present on #3160 but wasn't why we were getting a broken lock.

**Comment by clone1018** [comment]
What else do you want me to look for @whit537 ?

**Comment by whit537** [comment]
@clone1018 When you click "Certificate information" what do you see? Below is what I see. The problem on #3160 was that the signature algorithm was SHA-1 instead of SHA-256.

![screen shot 2015-03-23 at 1 18 50 pm](https://cloud.githubusercontent.com/assets/134455/6785917/3cac1068-d15f-11e4-8434-b6177efa1b2d.png)

**Comment by captn3m0** [comment]
I'm on `Chrome 43.0.2327.5 (Official Build) dev (64-bit)` and while I get the public audit warning, the padlock is green for me,

**Comment by whit537** [comment]
Closing because not reproducible with a stable version of Chrome. Reopen if it happens once 42 is stable.

**Comment by captn3m0** [comment]
I'm still on a dev-build (45), but I tracked down the issue to a a sha1 starcom SSL certificate somewhere in the chain. Here is a screenshot of the Startcom SSL certificate in the chain with SHA1 as the signature algorithm:

![screenshot_2015-07-03_16-09-50](https://cloud.githubusercontent.com/assets/584253/8497824/f4540cbe-219d-11e5-95a0-2bfb20e38be2.png)

This cert (StartCom) is valid till `10/25/17, 2:27:09 AM GMT+5:30`, which is why Chrome gives the warning. The list of domains in the gratipay cert is:

```
DNS Name: 0nfx8fkf.gratipay.com
DNS Name: gratipay.com
DNS Name: www.gratipay.com
DNS Name: gittip.co
DNS Name: www.gittip.co
DNS Name: gittip.com
DNS Name: gittip.org
DNS Name: gratipay.co
DNS Name: gratipay.net
DNS Name: gratipay.org
DNS Name: www.gittip.com
DNS Name: www.gittip.org
DNS Name: www.gittip.com
DNS Name: www.gratipay.co
DNS Name: www.gratipay.org
DNS Name: www.gratipay.net
```

I am guessing that this is a configuration issue on Heroku side?

**Comment by whit537** [comment]
@captn3m0 Why do you think it's Heroku? Sounds like a StartCom/Chrome interaction to me.

**Comment by captn3m0** [comment]
I was guessing it must be a mis-configuration issue on Heroku's side because that intermediary cert is clearly wrong. I was thinking it might be using an old cert config, but that seems unlikely as well.

**Comment by captn3m0** [comment]
I haven't ever used Heroku custom SSL, so don't really know much here.

**Comment by whit537** [comment]
I believe we are responsible for uploading the intermediate certificate bundle to Heroku. I guess we're using an out-of-date chain?

**Comment by whit537** [comment]
Weird. I'm seeing a SHA-256 signature algorithm for the intermediate certificate:

![screen shot 2015-07-09 at 8 29 43 pm](https://cloud.githubusercontent.com/assets/134455/8609912/7b4ce5b2-2679-11e5-8124-b1dd40b23be5.png)

I'm on Chrome 43.0.2357.132. What could explain the discrepancy?

**Comment by whit537** [comment]
It looks like the expiration timestamps differ as well.

**Comment by captn3m0** [comment]
Yes, I'm seeing green here as well for now. But once every few weeks this
gets red again because I get a sha1 cert in the chain.

**Comment by whit537** [comment]
Blech. Reminds me of https://github.com/gratipay/gratipay.com/issues/1512 and https://github.com/gratipay/gratipay.com/issues/2586. :disappointed:

**Comment by whit537** [comment]
If this is indeed parallel to #1512 and #2586, then I interpret this bug as a result of leaky abstraction. We have so very little hope of getting to the bottom of this, because it seems to be a bug somewhere in AWS, and we're insulated even from that by Heroku. To my way of thinking, the way to resolve this class of bugs is to port to an architecture that we control more directly.

**Comment by captn3m0** [comment]
Yeah. Maybe file a support ticket with heroku?

**Comment by whit537** [comment]
> We're seeing intermittent behavior—"once every few weeks"—where an out-of-date certificate is included in the chain for our SSL cert on https://gratipay.com/. The result is a broken trust indicator in Chrome. Here's [our public ticket](https://github.com/gratipay/gratipay.com/issues/3278) with more detail. How can we debug this?

https://help.heroku.com/tickets/251995

**Comment by stevo550** [comment]
@captn3m0 One thing to check: do you have any StartCom root certificates in your system certificate chain? You might see two with the common name "StartCom Certification Authority", one as SHA-1 and the other as SHA-256. I'm not sure which OS you are on, but I'm trying to find if [this post](http://blog.chromium.org/2014/09/gradually-sunsetting-sha-1.html) from the Chrome team is related. This certificate is issued under the SHA-1 root, so maybe it is taken that to mean insecure.

On Chrome 45/OSX I can't reproduce, so I wonder if it might related to your OS certs from this clause:

> Note: SHA-1-based signatures for trusted root certificates are not a problem because TLS clients trust them by their identity, rather than by the signature of their hash.

**Comment by captn3m0** [comment]
I do have 3 StartCom certs in my system certificate chain. I'm on arch linux. Only one of the 3 certs is a SHA1 cert, but its not the one being referenced above. (all 3 have CA=true)

The one breaking the ssl is a sha1 intermediate cert.

**Comment by captn3m0** [comment]
Ok, after much digging around (using the cert's name) I think I have understood the issue. 

- http://serverfault.com/a/685089/78192

>It's due to Windows' or Chrome's certificate cache. Because they (old and new intermediary cert) have the same name, the client will use the cached variant, which might be old and SHA1. The naming is StartCOM's fault. The bad caching is Windows' or Chrome's fault. They're not working very hard to fix it.

It makes perfect sense in my case because I'm very reluctant of clearing my browser cache. I copy my chrome profile over OS re-installs.

[This thread](https://forum.startcom.org/viewtopic.php?f=15&t=15741) on StartCom forums also has others facing the same issue.

Closing this issue as we can't really do anything about it for now.

**Comment by whit537** [comment]
Good debugging, @stevo550 @captn3m0, thanks.
