### ISSUE TITLE
get licensed as a money transmitter

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3321]
Reticketed from https://github.com/gratipay/gratipay.com/issues/3245#issuecomment-91112973 (cf. #938).

**Comment by whit537** [comment]
http://en.wikipedia.org/wiki/Money_transmitter
http://www.nmta.us/
http://moneytransmitterlicense.blogspot.com/
http://mortgage.nationwidelicensingsystem.org/Pages/default.aspx
http://moneytransmitterlaw.com/

**Comment by whit537** [comment]
> My name is Marco Santori. I’m a business attorney for technology companies. In particular, I represent digital currency businesses. I am also the Chairman of the Bitcoin Foundation’s Regulatory Affairs Committee. In this multi-part series, I will give a basic primer on the state of US law as it applies to digital currency entrepreneurs. I aim to help bitcoin businesses assess their risks and develop an informed business model.

Part I: Bitcoin Law: What US businesses need to know
http://www.coindesk.com/bitcoin-law-what-us-businesses-need-to-know/

Part II: Bitcoin Law: Money transmission on the state level in the US
http://www.coindesk.com/bitcoin-law-money-transmission-state-level-us/

Part III: Bitcoin Law: Compliance and Avoidance Strategies
http://www.coindesk.com/bitcoin-law-money-transmission-compliance-avoidance/

Is Bitcoin Legal?
http://www.coindesk.com/information/is-bitcoin-legal/

Lots of good info, even though we're not only exactly a "digital currency business."

**Comment by whit537** [comment]
Marco's firm: http://www.pillsburylaw.com/.

**Comment by whit537** [comment]
> Marco works closely with his clients to structure their business plans to comply with these regulations, and whenever possible avoid them entirely.

http://www.pillsburylaw.com/marco-santori

**Comment by whit537** [comment]
> The classic description of a money transmitter is a business, Business A, that accepts money from Person B and transmits that money to Person C, either at a later time or a different place.

http://www.coindesk.com/bitcoin-law-what-us-businesses-need-to-know/

**Comment by whit537** [comment]
> Because money transmission is such a heavily regulated business, classification as a money transmitter – especially unwitting classification – comes with real legal and practical consequences.

**Comment by whit537** [comment]
Eep.

![screen shot 2015-04-09 at 9 22 24 am](https://cloud.githubusercontent.com/assets/134455/7067531/f886a950-de99-11e4-9838-babfd2c37cc0.png)

**Comment by whit537** [comment]
> Whereas FinCEN regulators see themselves as money laundering preventers, state regulators see themselves as consumer protectors.
>
Thus, the application process is affectionately known among industry professionals as the "financial colonoscopy".

http://www.coindesk.com/bitcoin-law-money-transmission-state-level-us/

**Comment by chrisdev** [comment]
Here's an idea, set up a credit union or a co-op.

**Comment by whit537** [comment]
@chrisdev That sounds like getting licensed as a bank (#938), which I expect would be even more onerous.

**Comment by chrisdev** [comment]
@whit537 the US Bureaucracy really makes this credit union stuff sound like rocket science!!
 I actually found the link to the service that deals with Small Credit Unions http://www.ncua.gov/Resources/OSCUI/Pages/default.aspx
May be worth a shot

**Comment by whit537** [comment]
[IRC](https://botbot.me/freenode/gratipay/2015-04-09/?msg=36221814&page=1)

https://www.coinbase.com/legal/licenses

**Comment by bkrausz** [comment]
The do exist businesses that have MTLs and essentially license them out (essentially making you an agent of the business, allowing you to piggyback on their MTLs). I don't have specific names, nor do I know if it would enable your model (IANAL, yada yada), but may be worth exploring.

**Comment by bkrausz** [comment]
Asked a coworker: PreCash is the company I was thinking of.

**Comment by whit537** [comment]
Thnaks @bkrausz, will look into them.

http://www.precash.com/

**Comment by benhc123** [comment]
LibertyReserve.Com was money-laundering, but I think definitely we should need some sort of license to deal with money-handling.

**Comment by whit537** [comment]
The conclusion is baloney, but the rest isn't bad:

http://blog.wepay.com/marketplaces-and-money-transmitter-licenses/

**Comment by dpfavand** [comment]
I haven't been part of this discussion, so perhaps I missed something. But have you considered restructuring how Gratipay works so that instead of money transfers, people (backers, supporters) buy "Gratipay Coins" or something. Then the customer (backer, supporter) can give their "Gratipay Coins" to people they want to support. After that, the recipients can redeem their coins for a currency. Thus there are two (or three) transactions - one where a customer (supporter) buys coins from Gratipay, and one where Gratipay pays another customer (recipient) in currency for redeeming coins (and one where the supporter gives coins to a recipient, but it's not a currency transaction). Does that make any sense at all? Or is all the same as just being a money transmitter? Or an idea that you already looked at and discarded?

**Comment by whit537** [comment]
@dpfavand That idea has surfaced before. I don't know enough to say how that relates to money transmission, I don't think it necessarily gets you out of it, though. Anyway, this ticket is about getting licensed as a money transmitter, but that's not going to happen anytime soon due to cost. Closing in favor of https://github.com/gratipay/inside.gratipay.com/issues/192.

**Comment by techtonik** [comment]
@whit537 what is the cost?

**Comment by whit537** [comment]
Millions.

**Comment by techtonik** [comment]
Is there an official quote?

**Comment by techtonik** [comment]
Is there an official quote?

**Comment by whit537** [comment]
> In addition to the disclosure requirements, the financial obligations are substantial. A New York money transmitter must carry at least a $500,000 surety bond, and bonding agents will require a recurring yearly payment of 2-10% of the total bond amount, depending on the personal credit rating of the bond's guarantor.
>
An applicant must also satisfy minimum capitalization requirements that push well into the six figures. Add to that the cost of annual reporting, record-keeping, audits and legal fees. It should come as no surprise that (i) the costs of licensure, combined with (ii) the uncertainty of whether licensure is even required in the first instance, drive some businesses to not apply at all.

http://www.coindesk.com/bitcoin-law-money-transmission-state-level-us/

**Comment by ctrlcctrlv** [comment]
Surprise @whit537, I have reported you to FinCEN!

If you think you can just get away with operating Gittip illegally for three years and terminating random accounts you have got another thing coming. 

I hope they investigate your ass.

```
From: 8chan Admin <admin@8chan.co>
To: FRC@fincen.gov
Subject: Gratipay, LLC - Ambridge, PA based company operating illegal, unlicensed money transmission business
Date: Fri, 01 May 2015 10:39:17 +0800
Message-ID: <357624020.JBuKCSUl0u@localhost>
Organization: 8ch.net
X-KMail-Identity: 1363046236
X-KMail-Dictionary: en_US
User-Agent: KMail/4.14.7 (Linux/3.19.3-3-ARCH; KDE/4.14.7; x86_64; ; )
MIME-Version: 1.0
Content-Type: multipart/signed; boundary="nextPart2867216.RdcRsm78g5"; micalg="pgp-sha256"; protocol="application/pgp-signature"

--nextPart2867216.RdcRsm78g5
Content-Transfer-Encoding: quoted-printable
Content-Type: text/plain; charset="us-ascii"

Gratipay, LLC is operating an illegal, unlicensed money transmission bu=
siness=20
completely in the open.

Their payment processor, Balanced Payments, is shutting down (and might=
 also=20
be involved or complicit in the illegal acitivity).

Gratipay, LLC held funds from credit cards in escrow and then paid out =
Bitcoin=20
to me and others. I was paid out on five separate occasions, all to the=
 Bitcoin=20
address 1CBTiuoHhYwKKcrxsTQ3SmrKpJYALqfeVZ. The Blockchain TX IDs are l=
isted=20
below.

29a4a275abfc45577c25a7ab2417947d1e745afaecb78b16bd33999c02c55231
d820f294bd51ff61291873e1474750ea1f5c6acf4431be24c65d83c1c188daba
237e2c6fabaa20dd8c689f10fa0fcddc2539ec9c88d5cc562fdbc1ceab8f8564
28870c24a5810ea8341c3358503eb616f1c094d5edc00438018df93369351f9d
acdc354a29580a0502fe44c2234c7d503f697bca3b7fc30dd7384af85c5b5968
04edb2b139b934e44f0faaa8bf7663fda8d5e9fbe9bc02386ccd63bdc7ad6c7d

The total converted in US dollars of the illegal money transmission don=
e by=20
Gratipay, LLC just to me is $3,272 (13.7877095 Bitcoin)! MANY other dev=
elopers=20
on the Gratipay website accepted payments, I estimate that Gratipay pai=
d out=20
almost $100,000 in Bitcoin payments to completely anonymous people with=
 no=20
AML, KYC or any other process.

I am reporting this because Chad Whitacre, CEO of Gratipay, LLC termina=
ted my=20
account for no reason (it was giving him heat on social media), and the=
n I=20
researched his license status, and surprise, there is no license.

Gratipay is AWARE that they are operating without a license and has bee=
n=20
discussing what to do about this completely in the open on their forum.=


Gratipay wants to become a money transmitter because they are already e=
ngaged=20
in money transmission behavior:=20
https://github.com/gratipay/gratipay.com/issues/3321 (archived:=20
https://archive.is/d0KpY )

Gratipay determines that they ARE(!) a money transmitter, so is aiming =
to=20
change their service so that they dodge the heat:
https://github.com/gratipay/inside.gratipay.com/issues/192 (archived:=20=

https://archive.is/eKGmj )

Charlie Sherm recently went to jail for this exact behavior with his=20=

BitInstant business. I can only hope that an investigation into Gratipa=
y's=20
(formerly known as Gittip) activity is launched or already underway.

Please don't let this conman get away with this. Gittip, now Gratipay h=
as been=20
operating an unlicensed, illegal money transmission scheme for three ye=
ars.=20
For more details feel free to contact me, I have researched Gratipay, L=
LC=20
extensively.

--=20
Best,
Fredrick Brennan
8chan Administrator

--nextPart2867216.RdcRsm78g5
Content-Type: application/pgp-signature; name="signature.asc"
Content-Description: This is a digitally signed message part.
Content-Transfer-Encoding: 7Bit

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAABCAAGBQJVQudVAAoJEBDdyYOQGqGDVJcP/RtnnionDDb3x8Fh+imsWkd7
nD/4zkwIBOjeieyUCWUMEc7n1o2m5kYlVsn7EX4guBlW6c3v0igE5hoIJbWrFkL5
fxcHOUtJ7ZazWuai79voM0Ms9o4n+t+D4cXS3YFOkTOXEYT54NPGEVPOyRfEW8i3
Q5/ln7nYIauj6v/3QcJirgNBSdAnPpYRVFXmsoFMSifNVRfGcxfNE6/q6WmhGgUO
8Xu1XiU3zVb0mUZq/oY96mGBZgjVHQbNsvyxgTyWr5MpJZJvJXVcZR+y9JC2hmsr
Cv8gLDR9S6OSaT8+9HpVd0LoMVqi3cxZ5d4j2nGBBxiSGC90mvl2hOSLe9CLUfYf
jqmSbW0vbTdEwSqJFSrto1YsE7+oX0ugjYrS83RzuWBVPAAUpqXs/ZSVQyzJB34J
fHFIOFFcaeci5nU8d2cHdFXc4ljO2cTzUKrSqmx8IczveYiWRwPVygVILszofcXA
NG10F5EcjPbf6+a0oWZnY8aOiLoJnIxosM0YzMsdgA21U6XdMxaKvibB7XhDZee0
TfKPTqi+h8KoFLS+fUmPjg0tegDKVCKsryPbOC3vUMxlvOfJ+yGNGTb7d1w81m/1
4S6jdRWhpK3AYymnO91ZBc4UcWD50PIYDFuTiILXiOThuRwH1MFr9cdptGhGH7kb
C/dFptP5qt+w+MHLJlcL
=2VzJ
-----END PGP SIGNATURE-----

--nextPart2867216.RdcRsm78g5--
```

**Comment by ctrlcctrlv** [comment]
You banned me for commenting that I reported you to FinCEN, did you also ban me from commenting on your repo?

https://ghostbin.com/paste/d7gsc

Why don't you want your contributors to know I reported you to FinCEN? Afraid another will pull out like Changaco?

**Comment by techtonik** [comment]
@ctrlcctrlv so, it was you who reported Balanced to FinCEH and initiated its shutdown? And all of that just because laws are not ready for online services such as this, and because you can't maintain your Bitcoin wallet and get your $$$ out of it? What a mess..

**Comment by ctrlcctrlv** [comment]
@techtonik I didn't report Balanced to FinCEN, I reported Gratipay, LLC and its CEO @whit537 to FinCEN today. There is a difference. 

As soon as the Balanced Shutdown was announced @whit537 terminated mine and Andrew Aurenheimer (@rabite on Twitter) accounts. Ever since I've been investigating Gratipay, LLC and I finished my investigation with this FinCEN report (which I will also be mailing to the Pennsylvania Department of Banking & Securities). Before the shutdown was announced I didn't even know what Balanced was, I only learned that in the course of investigation.

>And all of that just because laws are not ready for online services such as this, and because you can't maintain your Bitcoin wallet and get your $$$ out of it? What a mess..

Speak for yourself. I can maintain a Bitcoin wallet just fine. My account was terminated for no good reason, thus my investigation and subsequent report.

**Comment by ctrlcctrlv** [comment]
I also made Spreedly, OpenACH and Braintree Payments aware of this report and @whit537's business conduct. https://twitter.com/HW_BEAT_THAT/status/593980954936377344

I am not doing this to mindlessly troll. I am doing this because I feel legitimately wronged by Gratipay, LLC and cursory investigation shows that Gratipay, LLC is in violation of federal law, and has indeed been such since Gittip was founded.

"All free software projects deserve gratitude, but some deserve more gratitude than others" should be the new Gratipay slogan. Shall I open an issue? :^)

**Comment by King-Snesker** [comment]
My browser tab reads 'get lice'.

**Comment by King-Snesker** [comment]
get lice

**Comment by King-Snesker** [comment]
https://secure02.kidshealth.org/parent/infections/common/head_lice.html
>You may be able to see the lice or nits by parting your child's hair into small sections and checking for lice and nits with a fine-tooth comb on the scalp, behind the ears, and around the nape of the neck (it's rare for them to be found on eyelashes or eyebrows).

My head is really itchy right now. You guys might want to get checked out. 

>A magnifying glass and bright light may help. But it can be tough to find a nymph or adult louse — often, there aren't many of them and they move fast.

**Comment by King-Snesker** [comment]
what in the cunting shit happened to my enterprise quality lice advice which is highly valuable and acutely on topic

$50 in illegal bitcoin transactions says the cripple did this

**Comment by techtonik** [comment]
@ctrlcctrlv yes, these laws were created before the internet era, and not for putting you in a jail for giving your friend $20 just because you want to tip him. But you can enforce this law as an US citizen. The only problem is that you seem to be from Philippines.

I can't say for sure that was reason for banning you, because I didn't watch closely. However, that happened after Chad under SJW pressure went to FBI (https://github.com/gratipay/inside.gratipay.com/issues/121) and asked them if the image board you're supporting is legal. They said that they do not give out information, only accept it. So, believe it or not, but FBI is involved. So can you clarify your status towards federal law? Why are you hiding in Philippines? It would be really interesting to discover that FinCEH cooperates with criminals to destroy innovative services that could provide some insights how to save the broken economy from collapsing when free resources are depleted, and prepare for the change in the regulation laws.

Also, can you post your investigation thesis "Gratipay as an illegal money transmission business" here? Gratipay is not PayPal. It is not a Bank, who are doing money transfers. Gratipay doesn't cut commissions, doesn't use people money for their own purposes, it can not speculate on currency conversion - that stuff is all handled by service providers. Why Gratipay should be licensed to let people tell their banks how to tip people? Sorry, but I am more dumb than you in money laundering and transmitting activities. Where is the edge when giving tips to people becomes "illegal business"? Also, can you describe that in human terms - I am not that ready to deal with bureaucracy and legalese, which was born by necromancers to steal people lifes before my age.

**Comment by ctrlcctrlv** [comment]
@techtonik Why bump this issue?

By the way I'm a US citizen.

Philippines has extradition to USA since the 80's. I'm not hiding here. If I wanted to hide I'd go to an Arab country with no extradition, not a former US colony ;)

I don't have to explain anything to you. Chad already kicked out most of his users, is demanding everyone give them their names and as such compiled with FinCEN. You lose, I await the European version of Gratipay. Just because you don't like money transmission laws doesn't mean you don't have to fllow them.

**Comment by ctrlcctrlv** [comment]
Also the FBI has even requested data from us before: https://8ch.net/_t/20150518.txt

Unlike Chad I don't have to be worried that the business I'm operating is illegal so I'm not afraid of the feds :)

**Comment by techtonik** [comment]
@ctrlcctrlv, hey, there is something that may help you out if your project is not acceptable for Gratipay - https://salt.bountysource.com/ - they don't have anything to do about economy of love and gratitude, so they don't have to meet the same challenges as we are.

**Comment by ctrlcctrlv** [comment]
Thanks for thinking of me, but I solved this by passing my lead developer status to a friend, @8n-tech ...

He's in charge of fundraising and development now, I'm just a lowly contributor (of both code and resources). ;)
