### ISSUE TITLE
How does the new Terms affect a plain Participant/User?

### ISSUE THREAD

**Issue by kaguillera** [gratipay/gratipay.com#3428]
So it took me two whole days to catch up on al that has transpired from the 8th May since I was away for a while.
Anyways maybe I did not read it all well but some things are a bit unclear. 
In the old ways of Gratipay I was a part of two teams and also got individual tips from a friends. Now I know that I would not get the individual tips anymore (due to the new model) and one of the teams I belong to does not fall under the "Open". That aside the last team I belong has been renew under the new model. 
My questions are as follows:
1.  As an individual who is getting tips from friends and/or family what will happen to me? (I know that this has been answered on other threads but I am just trying to cover all bases)  
2.  If I only belonged to an old team that is not accepted under the new model what happens to my account?
3.  If I belong to only belong to a team that has been accepted under the new model do I have to do anything?
         *  More specifically, do I have to reapply like the teams had to under the new model?
         *  Where and/how do I do that?
4. If I am in a combination of the above individual situation (which I actually am) how am I affected and what actions can I take, if any, as Gratipay moves forward in the restructuring process?

I know that some of these questions have been answered but some have not. I suggest apart from answering this comment/thread/issue directly that it should be emailed/posted/blogged/tweeted/etc somewhere so that users like myself know what is going on. 
Additionally I know that this is crunch time and this will not be a priority but I would like it to be noted that required preferably in the near future.

**Comment by whit537** [comment]
> I suggest apart from answering this comment/thread/issue directly that it should be emailed/posted/blogged/tweeted/etc somewhere so that users like myself know what is going on. 

I've added a +1 for you to #3419.

**Comment by whit537** [comment]
> Additionally I know that this is crunch time and this will not be a priority but I would like it to be noted that required preferably in the near future.

My immediate priority is cleaning up and finishing payday (#3415), and then writing up an announcement (#3419). Hopefully I can get to your questions this afternoon if no-one else gets to them first. :-)

Thanks for your understanding, @kaguillera, sorry for the disruption. :-(

**Comment by kaguillera** [comment]
Not a problem. Lets get through this first and then we can do clean up after. I just wanted to make sure it was noted so we don't forget.

**Comment by whit537** [comment]
We stopped processing payments entirely on May 13. We went out of business. We have only started processing payments again for people who have explicitly applied for a new Team. We haven't been pooling money for you since May 13, and if you take no other action then you will not receive any more payments through Gratipay. I see you have a small balance. This will be refunded in another month or two if you do not withdraw it first, either by applying for a one-time payout or joining a new-style Team. See #3539 and/or watch for a blog post about that in another couple weeks.

> 1) As an individual who is getting tips from friends and/or family what will happen to me?

If you were using Gratipay to receive tips that were not connected to a specific product or service that you provide, then unfortunately we aren't able to continue supporting you in that under Gratipay 2.0. The reason is that doing so would move us out of the "safe zone" of [the payment processor exemption to the definition of a money transmitter](https://github.com/gratipay/inside.gratipay.com/issues/201#issuecomment-111157623), and we can't afford to move out of that safe zone into the zone of direct regulation.

> 2) If I only belonged to an old team that is not accepted under the new model what happens to my account?

Your account will no longer receive any payouts, because old teams are no longer receiving or distributing payments.

> 3) If I [] only belong to a team that has been accepted under the new model do I have to do anything?
* More specifically, do I have to reapply like the teams had to under the new model?
* Where and/how do I do that?

We have not yet brought back our payroll feature that would enable teams to distribute funds like they did previously. That's going to take some work; keep an eye on #3433.

> 4) If I am in a combination of the above individual situation (which I actually am) how am I affected and what actions can I take, if any, as Gratipay moves forward in the restructuring process?

You should move your case (1) tips to a different platform (e.g., PayPal). For case (2) you should talk to the owner of the old team and ask them to apply for a new team. For case (3) you'll have to wait for us to bring back payroll.

**Comment by whit537** [comment]
What's left to close this, @kaguillera?

**Comment by kaguillera** [comment]
Nothing else left to close this ticket. Since I will have to wait on case 3 when payroll is brought back. So I am closing. I hope that a note has been made in a post/blog. I am closing unless someone else has anything to add.
!m @whit537

**Comment by whit537** [comment]
!m @kaguillera
