### ISSUE TITLE
turn off most subscriptions to Gratipay

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3502]
Most people who were giving to Gratipay were probably doing so because they were giving or receiving from someone else. It doesn't seem right that we're still taking their voluntary payments to us when we're no longer processing their *primary* payments. We should turn off all subscriptions to Gratipay for people that don't also subscribe to someone else.

**Comment by tshepang** [comment]
There is such a thing as being too noble. Please don't do this... you are forcing people to have to set tipping (again), and many may not even bother. Gratipay may end up with too little (of already very little) funding. To me it doesn't necessarily follow that, because I no longer receive funding, I stop funding others. You fund others primarily because they are doing good work.

One other thing: because people are being charged a lot less now, given they are no longer giving as much (there's few receivers now), they are not going to find themselves with less money than they used to have.

**Comment by rohitpaulk** [comment]
IMO, as long as they are notified that we're migrating the tips it should be fine.

**Comment by whit537** [comment]
Alright. Closing in light of your comments as well as this follow-up from the original poster:

> [This] is not exactly my case: I used to pay some people and decided to revive my payments (totally forgot to refill card that I used for Gratipay), but found out that the only target that I'd like and can support is Gratipay itself.

**Comment by tshepang** [comment]
@whit537 I thought  you were the original poster. Was it a private conversation?

**Comment by whit537** [comment]
Ah, yes. I see now that I neglected to link this (private) support request:

https://gratipay.freshdesk.com/helpdesk/tickets/2233

**Comment by tshepang** [comment]
So, was the first message here a quote, or was it your re-wording?

**Comment by whit537** [comment]
Not a quote. I extrapolated from it. Here is the original:

> It seems something's off with either your UI or mailing system. This email says that I support "readthedocs and 2 others" while in new UI (Gratipay 2.0) I support only Gratipay (not many options are available yet).
