### ISSUE TITLE
admins should be able to delete routes

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3548]
The url has `user.participant.username` in it instead of `participant.username`.
##

**Comment by rohitpaulk** [comment]
> The url has user.participant.username in it instead of participant.username.

Elaborate? I don't see where that is.

**Comment by whit537** [comment]
I think it's in JavaScript, `Gratipay.username` I think? When I try deleting a route through the UI as an admin I `POST` to `/~whit537/routes/delete.json` instead of `/~the-user/routes/delete.json`. I think it's in `js/gratipay/routes.js`.

**Comment by rohitpaulk** [comment]
Oh, okay I get it. I thought you were facing this problem with the [workaround](https://github.com/gratipay/gratipay.com/issues/3540#issuecomment-111305665), hence the confusion.

**Comment by whit537** [comment]
Ah. :-)

**Comment by kzisme** [comment]
@rohitpaulk I suppose I'll begin here.  

To make sure I'm understanding correctly - Deleting routes is referring to deleting payment routes within the ~user that is currently logged in.  (Not another user)

Such as here:
<img width="1280" alt="screen shot 2015-12-20 at 16 27 31" src="https://cloud.githubusercontent.com/assets/3493562/11948734/4535d6d4-a845-11e5-8188-5d2b5b6f2ff7.png">

The change that needs to be done refers to [this](https://github.com/gratipay/gratipay.com/blob/master/js/gratipay/routes.js#L39) line and it should reflect the suggested change @whit537 made....or am I over simplifying this? 

Also what is the preferred method of testing Ajax calls?  I've used Chrome Dev Tools in the past - but I'm just curious.

**Comment by rohitpaulk** [comment]
> To make sure I'm understanding correctly - Deleting routes is referring to deleting payment routes within the ~user that is currently logged in. (Not another user)

No, not exactly. Deleting routes works just fine for the ~user that is currently logged in. The bug is that deleting routes doesn't work as intended when an admin uses it. As an admin, you should able to visit `~bob`'s page and delete his route. If you try that on `~bob` now (when signed in as `~kzisme`) though, it'll end up deleting your route, and not `~bob`'s. 

> The change that needs to be done refers to this line and it should reflect the suggested change @whit537 made....or am I over simplifying this?

I don't think it's *that* simple :) 

Did you have a look at https://github.com/gratipay/gratipay.com/issues/3548#issuecomment-111306137? 

> Also what is the preferred method of testing Ajax calls? I've used Chrome Dev Tools in the past - but I'm just curious.

Chrome dev tools works just fine for me...
