### ISSUE TITLE
Receiving payments in new version unclear

### ISSUE THREAD

**Issue by thomasdavis** [gratipay/gratipay.com#3556]
Hi there, thanks for all the great work guys.

I couldn't quite deduce how the new system works. 

On my organizations profile (https://gratipay.com/~jsonresume/) it says it receives xx per week. But when I look at the history tab, it says it hasn't received anything since April.

Have payments commenced since the switch?
Do the people who were originally donating have to sign up under the new system?

#### Notify
- [ ] https://gratipay.freshdesk.com/helpdesk/tickets/2450
- [ ] https://gratipay.freshdesk.com/helpdesk/tickets/2534
- [ ] https://gratipay.freshdesk.com/helpdesk/tickets/2591

**Comment by dcht00** [comment]
@whit537 It just occured to me for the first time that during "gratipocalypse", it was not only that we weren't getting paid. It was that the money was not accumulating on our accounts.
That's a pretty serious and unfortunate miscommunication.

**Comment by whit537** [comment]
> That's a pretty serious and unfortunate miscommunication.

@dcht00 I'm sorry. :-(

**Comment by whit537** [comment]
> Hi there, thanks for all the great work guys.

@thomasdavis Hi! Thanks! :-)

> I couldn't quite deduce how the new system works.

Sorry for the confusion. :-/

> On my organizations profile (https://gratipay.com/~jsonresume/) it says it receives xx per week. But when I look at the history tab, it says it hasn't received anything since April.

Yeah, sorry, we need to bring the giving/receiving numbers (reticketed as https://github.com/gratipay/gratipay.com/issues/3560) and the history page (+1 added to https://github.com/gratipay/gratipay.com/issues/3455) up to speed.

P.S. You can see how we're prioritizing things on our weekly [Radar](https://github.com/gratipay/inside.gratipay.com/labels/Radar) tickets. Here's [this week's](https://github.com/gratipay/inside.gratipay.com/issues/251). At our current velocity I estimate we'll get to these issues in three weeks or so (PRs always welcome, of course).

> Have payments commenced since the switch?

Yes! I am seeing that the [JSON Resume](https://gratipay.com/json-resume/) team is owned by [~thomasdavis](https://gratipay.com/~thomasdavis/) (not ~jsonresume), and I do see payouts on the history page there. No?

We're starting to talk at https://github.com/gratipay/gratipay.com/issues/3399#issuecomment-112110512 about cleaning up the team/owner/member ontology in Gratipay 2.1.

**Comment by mattbk** [comment]
@thomasdavis, this doesn't directly address your question, but might help clarify some things.

[There are now team pages and individual pages](https://github.com/gratipay/inside.gratipay.com/issues/278#issuecomment-118278255), something I hadn't understood until I read the linked comment.  Apparently, all the individual payments sent and received before Gratipocalypse are still there on the individual page.  I don't see any way to check these on the team page (even my own, to which I theoretically should have access).

Example:
https://gratipay.com/json-resume/ is a team page, which says it is owned by thomasdavis
https://gratipay.com/~thomasdavis/ is a individual page
https://gratipay.com/~jsonresume/ is another individual page, presumably from before Gratipocalypse?

Possible related tickets (to create if none related exist):
- Clarify on the website how teams and individuals work (because it's not clear).
- Add payments/received history to team pages (because if Gratipay is about teams, isn't that where the money stuff should be tracked?)
- Communicate clearly to each approved team whether or not they are receiving money at each payday and why they may not be receiving what they used to be receiving (should be UI and part of team approval process)
- List on individual page what teams they are a part of/owners of.  I think there is a lot of confusion about why you can't go to an old profile (e.g., https://gratipay.com/~jsonresume/) and not see a way to donate.
- Probably a lot more.

**Comment by thomasdavis** [comment]
Thanks @mattbk that helps!

So my main questions are:

1) My donors after Gratipocalypse stopped sending that money as soon as it happened? As in there is no funds in escrow or something.

2) If my donors before Gratipocalypse haven't signed up again, they will no longer send money?

**Comment by mattbk** [comment]
+1 from https://twitter.com/espadrine/status/616188871651524609

**Comment by mattbk** [comment]
+1 from https://gratipay.freshdesk.com/helpdesk/tickets/2450

**Comment by kzisme** [comment]
So, @mattbk let's try to condense what we want to work on I suppose.

My thoughts are:
1. General overview (ie: Individual Gratipay user - why use this service over a simple donation)
2. Difference between Team and Individual accounts.
3. Clearly show where/who/how much is being sent or received to teams/individuals (#3455 deals with this a little)

I also feel like this could be talked about more here: 

>This does exist on individual profiles. I think there is a lot of confusion about why you can't go to an >old profile (e.g., https://gratipay.com/~jsonresume/) and not see a way to donate.

Also!  

Created an updated FAQ - or even a "Getting Started with Gratipay 2.0" would be nice.  It would probably eliminate a lot of these PR's otherwise.

**Comment by whit537** [comment]
@thomasdavis @mattbk @kzisme What if we link PayPal payout routes directly to Teams? Would that help us get rid of the confusing user(owner)/Team distinction?

**Comment by kzisme** [comment]
@whit537 @thomasdavis  @mattbk  How are payouts currently linked to teams?  

My current thinking is that:
- As an individual you can create an account to send/receive.
- You can create a team account to send/receive, but are the funds dispersed to the members of the team?  If they aren't is a 'Team Account' just meant to represent a certain entity/organization? 

I just connected my individual Gratipay account with Github and joined the Gratipay community, so I guess a distinction should be made between Teams/communities as well.

**Comment by kzisme** [comment]
It seems as though within each team they can choose how they want to 'Share their revenue'.  Also how close are we to working out #3433?

**Comment by whit537** [comment]
> How are payouts currently linked to teams?

All money goes to an Owner, which is a ~user account (i.e., a record in the `participants` table). It's just the ~user that has a payout route right now.

Team and Individual keeps coming up as a distinction. It's not the right one. The distinction we want to make is between:

 1. Companies that are **receiving** money ("payments") and **redistributing** it ("payroll").
 1. Entities (could be an individual or a company) that are **sending** money.

The opposite of Team is Individual, so that's confusing. What's a better pair of terms to use here?

**Comment by whit537** [comment]
> Also how close are we to working out #3433?

Not close. :-(

I see us spending the next month or two a) cleaning up bugs to bring Gratipay back up to beta quality, and b) dealing with escrow (#1383, #3539). Not until we have that stuff cleaned up can we even start on the [hard work](https://github.com/gratipay/inside.gratipay.com/issues/283#issuecomment-118841626) it will take to bring back payroll. Honestly? It could be a year.

**Comment by stevepiercy** [comment]
> The opposite of Team is Individual, so that's confusing. What's a better pair of terms to use here?

@whit537 Suggest "Entity" and "Member".

**Rationale**

* Entities may consist of either companies, persons, or organizations.
* Entities may hold intellectual or property rights (copyright and licensing) on the Work Product.
* Entities are taxable and are responsible to report income and expenses associated with the Work Product.
* Entities may receive money (Payments) for the purpose of redistributing it (Payroll) to its Members.
* Members perform work on a Work Product for the benefit of the Entity.
* Members receive payments from an Entity in exchange for performing work.
* Members are responsible for reporting income and paying any taxes.

However, there is another type of Entity not mentioned: the loose Association of developers who contribute work to a FOSS project. The Association lacks any legal status, as well as the resources to attain legal status (no Social Security Number, Employer Identification Number, Articles of Incorporation, Bylaws, bank account, business license, etc.). PayPal can and does freeze assets for such Associations. Maybe an Association is an Entity, or it doesn't fit the Gratipay model, or something else?

For these reasons, for my specific Entity, KnopProject, and its Owner ~KnopProject, I do not wish to create a new PayPal account.

**Comment by mattbk** [comment]
@stevepiercy Good comments, especially concerning PayPal's specific rules.

As I understand it right now (because no payroll), the function of Teams is to funnel money to Owners, who are then responsible for disbursing it.

The reason I bring up the Team/~user distinction is because that's the way it is set up right now--there is a specific page for each, so they appear as different classes of entities to any random person online.

What I would like to see is a slight revamp of the ~user page (or general treatment of ~users in copy) that clarifies what is happening.  "This is a ~user profile.  He or she is paid for work on these teams [x, y, z], so please support him/her there."  I understand that I'm hamstrung by knowing how things used to work, but on a site that is ["a way to give money every week to people and teams you believe in,"](https://gratipay.com/about/) it's confusing to not be able to give money to a person, especially when I can see a profile that may still (post 1.0) explain what this person is doing and where contributions will be used.

**Comment by stevepiercy** [comment]
> As I understand it right now (because no payroll), the function of Teams is to funnel money to Owners, who are then responsible for disbursing it.

I looked all over the UI for a way to add Members/Owners to the Team, but found none. How can I do this? I cannot add my own ~user StevePiercy to the Team KnopProject.

This also means I also have no way to disburse any funds, even if I had any to disburse.

>"This is a ~user profile. He or she is paid for work on these teams [x, y, z], so please support him/her there."

It is my understanding that we do not give money to individuals anymore nor in the future. Even in history, people gave money for my work (what I do), not me as an individual (who I am).

> "a way to give money every week to people and teams you believe in"

As an aside, "belief" ruffles my feathers. I think Gratipay is a way to show gratitude for the work that people and teams produce by giving money every week. "Belief" has religious connotations for me.

**Comment by mattbk** [comment]
> I looked all over the UI for a way to add Members/Owners to the Team, but found none. How can I do this? I cannot add my own ~user StevePiercy to the Team KnopProject.

I think this is a function of #3433.

**Comment by mattbk** [comment]
This may merit a different ticket (because it's about pay*outs*, not pay*ments*), but it also looks like no tips are moved if there it not a valid payout (=transfer out of Gratipay) method available.  At this time the only option for payouts is PayPal.

- E.g., ~Alice gives $3/week to Team B (owned by ~Bob), but ~Bob doesn't have a PayPal account set up, so $3 is neither deducted from ~Alice's account nor added to the B Team and distributed to ~Bob.  If ~Bob adds his PayPal account, he'll start receiving those Team B donations, but he will _not_ receive any donations that ~Alice intended during the weeks where no payout method was in place.
- E.g. https://gratipay.freshdesk.com/helpdesk/tickets/2405, wherein the ~user wants to know why money is not accruing in his account while he lacks a payout method.

This seems like a situation where escrow would be good to have (see additional discussion at https://github.com/gratipay/gratipay.com/issues/1383), but there is no telling when (if ever) ~Bob will add a payout method.

**Comment by whit537** [comment]
> However, there is another type of Entity not mentioned: the loose Association of developers who contribute work to a FOSS project. The Association lacks any legal status, as well as the resources to attain legal status (no Social Security Number, Employer Identification Number, Articles of Incorporation, Bylaws, bank account, business license, etc.). PayPal can and does freeze assets for such Associations. Maybe an Association is an Entity, or it doesn't fit the Gratipay model, or something else?

This is an important paragraph. I feel as if we're standing at the edge of a cliff, gazing across and wondering how we will ever traverse it. The gulf is between the FOSS communities "soft" understanding of what a project entails—a loose Association as @stevepiercy ably describes it—and the "hard" understanding of what a corporation or organization is under the law. Gratipay 2.0 is about bridging that gap. Our asymptote is [a Stripe-like "company as a service" abstraction](https://github.com/gratipay/inside.gratipay.com/issues/211#issuecomment-109518669). That's a :hankey:-ton of work, however, and we're triply bootstrapping. We're going to be slow getting there. Good thing you're patient, @stevepiercy. :-)

**Comment by whit537** [comment]
> I couldn't quite deduce how the new system works.

@thomasdavis Thanks for your patience as we clean this all up. We now have a fresh visual design, rewritten [About](https://gratipay.com/about/) pages, and correct giving/receiving numbers on Team and ~user profiles:

https://gratipay.com/jshttp/

Does this help address your issue? What else do we need on this ticket before we can close it?

**Comment by whit537** [comment]
Sorry, linked to the wrong Team page. :-)

https://gratipay.com/json-resume/
https://gratipay.com/~thomasdavis/

**Comment by whit537** [comment]
Gonna go ahead and call this one good. If something is still unclear feel free to say so, @thomasdavis! :-)
