### ISSUE TITLE
update giving/receiving numbers in sidebar

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3560]
Reticketing from @thomasdavis at https://github.com/gratipay/gratipay.com/issues/3556#issue-88236989:

> On my organizations profile (https://gratipay.com/~jsonresume/) it says it receives xx per week.

**Comment by whit537** [comment]
+1 https://gratipay.freshdesk.com/helpdesk/tickets/2354

**Comment by rohitpaulk** [comment]
A note: This isn't 'high priority' thanks to https://github.com/gratipay/gratipay.com/commit/7b488e216b11086ce512b24b1b3cef98895b4def. I initially thought of working on this after we brought back Payroll (coz we'd have to modify it then anyway), but now it does make sense to fix it before that.

**Comment by mattbk** [comment]
Under 2.0, should teams show only receiving, and individuals show only giving?

I think it is especially important for approved teams to have a "receiving" amount in order to show that yes, things are working, and yes, if your team is approved, you too will be receiving funding.  For example, I set a small tip/subscription/support/whatever-it-is-called-now for an approved team which shows up to me, but not to anyone else.

I know there is a lot under the hood that needs to be dealt with for 2.0, but approved teams are the "showcase" for how the new system is supposed to work, so making it look like things are working is important.

**Comment by whit537** [comment]
> Under 2.0, should teams show only receiving, and individuals show only giving?

Individual can still receive, but certainly receiving is the focal number for teams, and giving for individuals (more properly ~users since companies like https://gratipay.com/~teespring/ etc. can be givers).

**Comment by mattbk** [comment]
What is the mechanism by which ~users (I'll try to use the right terminology) can receive, if payroll does not exist yet under 2.0?

**Comment by whit537** [comment]
@mattbk Nearly correct. Two changes:

1. I don't believe we have this: "Team money sent comes out of Owner's credit card." Where are you seeing that?
1. As mentioned above, "~users" is more accurate than "Individuals." https://gratipay.com/~teespring/ is a ~user but not an individual.

**Comment by mattbk** [comment]
@whit537 I assumed that if a Team had $0 and tried to donate to another Team, the money had to come from somewhere.

**Comment by mattbk** [comment]
If ~users cannot receive donations, I think it would be appropriate to add the list of Teams they are on to the sidebar in place of the donate button.  Then the UX is the same, regardless of what type of page you are looking at: if you want to donate, look left under the avatar.

**Comment by mattbk** [comment]
I don't have a build in front of me right now to check, but does https://github.com/gratipay/gratipay.com/pull/3663 help solve this issue (if you revert https://github.com/gratipay/gratipay.com/commit/7b488e216b11086ce512b24b1b3cef98895b4def)?

**Comment by whit537** [comment]
> update giving/receiving numbers in sidebar

Done in #3721.
