### ISSUE TITLE
link PayPal to close flow is confusing

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#3627]
From https://gratipay.freshdesk.com/helpdesk/tickets/2162:

> it won't let me close til I add and verify a PayPal account. But clicking the add button just takes me to a page that says my paypal account is not connected and that I need to add and verify a paypal account, and clicking that link takes me back to the page where the "add" button is.
##

**Comment by whit537** [comment]
@mattbk The confusion here is that the user needs to add a verified email before they can specify that email as their *PayPal* email, but our workflow is confusing. Here's what they're seeing:

![screen shot 2015-07-20 at 7 48 15 pm](https://cloud.githubusercontent.com/assets/134455/8790144/4a7fa4cc-2f18-11e5-820f-5d26f8d76493.png)

They click on "link a PayPal account" and see:

![screen shot 2015-07-20 at 7 48 32 pm](https://cloud.githubusercontent.com/assets/134455/8790150/559d5d4a-2f18-11e5-8fae-3179940b66a3.png)

The click on "add and verify" and see:

![screen shot 2015-07-20 at 7 49 41 pm](https://cloud.githubusercontent.com/assets/134455/8790165/803bdf40-2f18-11e5-95a3-1c1d29e51993.png)

And they are (understandably) focused on the "Add" button opposite the PayPal logo, rather than the "Add email address" button.

**Comment by whit537** [comment]
**HOWEVER**, for this particular user I think we should issue them a refund inside Balanced rather than requiring them to attach a PayPal. Will pick up over on Freshdesk and leave this ticket for the confusing UI ...

**Comment by tswast** [comment]
I tried to apply for a new team and was confused as well, since I did not see PayPal listed as one of the account link options (Bitcoin and Venmo were there, though). I eventually found it through the "Routes" link, but I didn't know that was how to receive payment until I clicked through. Maybe "Payment Routes" isn't the clearest of terms.
