### ISSUE TITLE
revise team application

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3679]
Now that we have received 79 applications, let's think about some tweaks to the application to make sure it's doing what we want.

I think the **product or service** question is pretty straightforward and I think is fine.

**Revenue model** tends to see these three responses:

 - "We ask people for money."
 - "We have no revenue model."
 - @wout's [answer](https://github.com/gratipay/applications/issues/15) :)

This question is controversial, but I think that means it's working as intended. The point of this question is to filter out people who are thinking in terms of building a viable open business from those who aren't.

For **Contributing** I think we can drop back from an open-ended textarea to a link to contributor documentation or at least an issue tracker. We should specify that this is where we expect to find a list of available open work that's ready to start without having to explicitly apply first.

**Paying contributors** really comes down to "kids eat first" or "parents eat first." I think we should allow both when we bring back payroll (#3433), and this part of the application will simply be a select between those two options. One pattern we're seeing is that nobody is making any revenue, so they aren't at a place where they can really think about sharing it. They're reluctant to make promises to share revenue when they themselves are not receiving enough yet. I think we want to keep "everyone sets their own take" but allow for "parents eat first."

**Comment by mattbk** [comment]
> The point of this question is to filter out people who are thinking in terms of building a viable open business from those who aren't.

This implies that you only want people who have any sort of business sense and are focused on that area rather than doing whatever it is that they do.  If the goal of Gratipay is to help push open projects (meaning minimum barrier to contribution), why are we setting a barrier to entry of "treating this project as a moneymaking endeavor"?

That's not to say we shouldn't ask about revenue model, but maybe it should be phrased in such a way as "Many teams currently have no revenue stream.  If your team started generating revenue through Gratipay, how would you spend it?"  *But* what is the answer that "fits" with Gratipay's mission and brand guidelines?

**Contributing** looks good, and I think the criteria of "Does this team have a well-documented method for new people to contribute" is _much_ stronger for accept/close team choices.  

(The [TechRaptor model](https://github.com/gratipay/applications/issues/17) of "Send us your contribution and we'll decide whether it fits" is, IMHO, within the bounds of Gratipay in the same way I can submit a PR to any project on GitHub--although not all GitHub projects have documentation explaining how people can get involved.)

**Comment by mattbk** [comment]
Darn it, here I am mixing policy discussions into the technical side of things.  Didn't mean to do that.

**Comment by whit537** [comment]
> Darn it, here I am mixing policy discussions into the technical side of things. Didn't mean to do that.

No! Your comment is fine here. The proposal on this ticket is to modify code, specifically our application form, and of course that does get us into some policy questions.

**Comment by whit537** [comment]
Actually, you're right. Let's close this as a dupe of #3677.

**Comment by whit537** [comment]
Sorry. :)
