### ISSUE TITLE
Show when a project is misconfigured

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3727]
Reticketed from https://github.com/gratipay/gratipay.com/issues/3666#issuecomment-136153083.

When a Team's payout route fails or is disconnected (cf. #3681), then we should reflect in the UI the fact that the Team isn't actually receiving payments:
- The Giving page should include a "Broken"(?) tab in addition to the Active and Cancelled tabs.
- The `giving` and `receiving` caches shouldn't include broken payments.

What are the conditions for successful payment? How else can payments be broken?
##

**Comment by whit537** [comment]
> "Broken"(?)

Maybe "Inactive" to parallel "Active"?

**Comment by whit537** [comment]
The point is that it *would* work except for a circumstance outside of the giver's control (and probably inside of the giver's control—though, consider Team rejections).

**Comment by whit537** [comment]
I'm not going to get to this on the Pivot milestone.

**Comment by whit537** [comment]
I've created a new Refund Announcement milestone (see https://github.com/gratipay/inside.gratipay.com/issues/326#issuecomment-136349981) and added this to Pivot.

**Comment by aandis** [comment]
Thinking about landing this next. Here's how I think to go about this

1. Create a `has_payout_route` column in `payment_instructions` which would be `true` if owner of the `team` has paypal set up and `false` otherwise.
2. Calculate `receiving` of the team taking into consideration only those rows of `payment_instructions` where `is_funded` is `true` *and* `has_payout_route` is `true`.
3. Calculate `giving` of the participant taking into consideration only those rows of `payment_instructions` where `is_funded` is `true` *and* `has_payout_route` is `true`.
4. Reflect all `payment_instructions` where `has_payout_route` is `false` or `is_funded` is false on the `Inactive` tab of the `Giving` page.

Suggestions?
cc: @whit537 @rohitpaulk

**Comment by aandis** [comment]
> Here's how I think to go about this ...

This is all well and good but I still don't understand how https://github.com/gratipay/gratipay.com/issues/3666#issuecomment-136153083 could happen. 
> According to my "Giving" page, I'm giving to two teams, but the summary seems to only take one into account

Reason mentioned in https://github.com/gratipay/gratipay.com/issues/3666#issuecomment-136227364 is
> That could be because the ~owner of the other Team you give to doesn't have a PayPal attached (#3681),

But this can't be because till now we *don't* check whether owner has paypal set up while calculating `giving` amounts for participants. I am only proposing to add it now.

**Comment by mattbk** [comment]
Changing the payday algorithm last year affected a bunch of things. Right now, ~book's page doesn't even report him as giving at all, which is not true. @aandis, do you have admin access to be able to see ~user information at gratipay.com?

**Comment by aandis** [comment]
> ~book's page doesn't even report him as giving at all, which is not true

It's not? Why would that be?

> do you have admin access

Nope. I can see ~book giving $0.00

**Comment by mattbk** [comment]
@whit537, can we give @aandis the admin bit so he can see how Gratipay.com is actually behaving?

**Comment by whit537** [comment]
Done! Welcome to the League of Admins, @aandis. With great power comes great responsibility! :-)

```
=> select username, is_admin from participants where is_admin;
┌────────────┬──────────┐
│  username  │ is_admin │
├────────────┼──────────┤
│ clone1018  │ t        │
│ rohitpaulk │ t        │
│ aandis     │ t        │
│ whit537    │ t        │
│ mattbk     │ t        │
└────────────┴──────────┘
(5 rows)
```

**Comment by aandis** [comment]
woah. ****chiils****. Thanks @whit537 :)

**Comment by aandis** [comment]
> ~book's page doesn't even report him as giving at all, which is not true

@mattbk I see now. But I think this behavior is correct since ~book doesn't have credit card setup. So showing $0.00 in `giving` makes sense. Only thing wrong is that `payment_instruction` are shown in the `Active` tab. They should instead be shown in the `Inactive` tab which would happen once this issue is resolved.

**Comment by mattbk** [comment]
That's the part that's confusing to me (and maybe to ~book). If a ~user is taking from a team and has enough to cover giving, it's confusing that their tips don't work. This must have been explained to me before.

Moving "unfunded" into inactive makes sense in this case. It should definitely be clear why this is the case (help text on Inactive tab) and an alert added if there isn't one yet (something scary like "your account is broken and you aren't tipping anyone).

Additionally this is one of the things I think we should email people about on payday. Do we do that already? "You  are attempting to give but we can't do that because x."

**Comment by whit537** [comment]
Bump. One of four left on Finish Team Basics. Update, @aandis?

**Comment by aandis** [comment]
What I have [proposed](https://github.com/gratipay/gratipay.com/issues/3727#issuecomment-193297891) should work except that it'll also need to take care of - 

> If a ~user is taking from a team and has enough to cover giving, it's confusing that their tips don't work.

I am going to have to go over payday to understand how it handles that so that the actual numbers match with what is supposed to happen at payday.

**Comment by kaguillera** [comment]
@aandis I was just wondering if you had any progress on this. Just curious...

**Comment by mattbk** [comment]
I recently saw a comment by @rohitpaulk that explained (to a user) how this worked, but I can't seem to locate it...

**Comment by aandis** [comment]
@kaguillera I did intend to start this but didn't get a chance to go over payday.

**Comment by aandis** [comment]
Although I give to gratipay, my [giving](https://gratipay.com/~aandis./) doesn't reflect that. I realize this issue is about misconfigured teams, but I couldn't find an issue about user's misconfigured caches. Is there an existing issue for this?

**Comment by whit537** [comment]
Hmm ... maybe https://github.com/gratipay/gratipay.com/issues/4064 or https://github.com/gratipay/gratipay.com/issues/4120?

**Comment by mattbk** [comment]
@aandis, didn't you answer this yourself at https://github.com/gratipay/gratipay.com/issues/3727#issuecomment-193427152?

**Comment by aandis** [comment]
@mattbk that was before I realized that if a user's `takes` is enough to cover his `giving`,  he'll actually be able to give to that team on payday irrespective of whether he has a cc setup or not. So since ~book takes from multiple teams and has enough to give to other teams, his `giving` should show the amount given.

**Comment by whit537** [comment]
> When a Team's payout route fails or is disconnected

Actually, we still collect even when the route is failing. 🐭

In any case, I'm dropping this from the "Finish project basics" milestone because I think don't need to block other work on it.

**Comment by mattbk** [comment]
Digging into https://github.com/gratipay/gratipay.com/issues/4367 and finding similar behavior to [this](https://github.com/gratipay/gratipay.com/issues/3727#issuecomment-253822840):
> Although I give to [project], my giving doesn't reflect that.

@aandis, as a fellow team member, I'm going to use your simple giving/taking as an example. You're receiving from Gratipay, and giving an equal amount to Gratipay (!):
![image](https://cloud.githubusercontent.com/assets/3729038/23617598/395fa31c-0253-11e7-9c3a-bd26f6481156.png)

...but your giving doesn't show up. Mustn't this be because you don't have a credit card attached?
 ![image](https://cloud.githubusercontent.com/assets/3729038/23617644/56b4fe6c-0253-11e7-9b00-69c46b283d6d.png)

**Comment by mattbk** [comment]
> Additionally this is one of the things I think we should email people about on payday. Do we do that already? "You are attempting to give but we can't do that because x."

Also, "We have money for you, but can't payout because you have no route set up."

**Comment by mattbk** [comment]
I guess it should be opt-in like other emails, e.g.,

![image](https://cloud.githubusercontent.com/assets/3729038/24763390/d5ed79c2-1ab6-11e7-92b4-1900935d25b0.png)
