### ISSUE TITLE
Wrong payout?

### ISSUE THREAD

**Issue by anselmh** [gratipay/gratipay.com#3756]
Hi guys,

[my profile states $34.65](https://gratipay.com/~Anselm%20Hannemann/) as receiving but the history and payouts show only $27.65 for the last two payouts. Did I miss something or is this a bug?

Thanks,
Anselm

**Comment by whit537** [comment]
Sounds like a +1 for https://github.com/gratipay/gratipay.com/issues/3612 and https://github.com/gratipay/gratipay.com/issues/3729. :-)

**Comment by whit537** [comment]
Leaving open until we land those tickets so we can see clearly to answer the question here.

**Comment by whit537** [comment]
+1 from @book at https://github.com/gratipay/gratipay.com/issues/3666#issuecomment-136153083:

> the "Takes" total is different from what I actually receive each week.

**Comment by whit537** [comment]
When @anselmh and @book reported this issue it would've been due to failing credit cards week to week: providing better visibility into that is #2534 (see also the meta-ticket #3171). Since then we've added *another* source of discrepancy between "Takes" on the chalkboard and the amount actually received: charging in arrears. Communicating better about that comes under https://github.com/gratipay/gratipay.com/issues/3612. Closing this with +1s added to #2534 and #3612.
