### ISSUE TITLE
make pytest: You tried to register an orm model for typname elsewhere_with_participant, but no such type exists in the pg_type table of your database.

### ISSUE THREAD

**Issue by fenryxo** [gratipay/gratipay.com#3789]
Hello. I've tried to run a Python test suite (`make pytest`) and there are 38 errors coming from `db.register_model(model)`, for example:

```
tests/py/test_api_key_json.py:7: in <module>
    from gratipay.testing import Harness
gratipay/testing/__init__.py:18: in <module>
    from gratipay.main import website
gratipay/main.py:64: in <module>
    website.db = gratipay.wireup.db(env)
gratipay/wireup.py:57: in db
    db.register_model(model)
env/lib/python2.7/site-packages/postgres/__init__.py:637: in register_model
    raise NoSuchType(typname)
E   NoSuchType: You tried to register an orm model for typname \
elsewhere_with_participant, but no such type exists in the pg_type \
table of your database.
```

**Comment by yifeiwu** [comment]
+1 Getting 38 errors as well when I pull from the current master branch.

**Comment by whit537** [comment]
I'm able to reproduce this error like so:

```
[gratipay] $ dropdb gratipay-test
[gratipay] $ createdb gratipay-test
[gratipay] $ make pytest
```

The fix is to run `make test-schema` before running `make pytest`. The `test-schema` phony target is a dependency of `test`, but not of `pytest`. I've made a PR (#3797) to push the dependency down to both `pytest` and `jstest` (see #3684 for folding `jstest` into `pytest`).
