### ISSUE TITLE
is arrears charging right?

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3827]
Why am I getting charged $20.74 when I only have $10.69 in giving?

![screen shot 2015-10-15 at 8 34 35 pm](https://cloud.githubusercontent.com/assets/134455/10531135/46cc74ba-737c-11e5-9b2c-8ff71a747ad0.png)

![screen shot 2015-10-15 at 8 35 08 pm](https://cloud.githubusercontent.com/assets/134455/10531136/47fb77a0-737c-11e5-9723-087949724c77.png)

**Comment by rohitpaulk** [comment]
It is charging right. Looks like - last week your giving was under $10, so you weren't charged and it went into dues. You increased your giving this week (before being charged) - and you finally got charged the dues (< $10) + this week's giving (> $10). 

(I remember this because I was using your profile to test the dues UI).

**Comment by whit537** [comment]
Heh. :-)

Thanks, @rohitpaulk. And now since I'm over the $10 threshold I don't see the dues column that I would've seen had I checked last week, ya?

**Comment by rohitpaulk** [comment]
Exactly :)

**Comment by whit537** [comment]
Cool, thanks. :-)
