### ISSUE TITLE
Donation button missing

### ISSUE THREAD

**Issue by riseupdotnet** [gratipay/gratipay.com#3853]
Hello,

For some reason that I cannot seem to figure out, there is no donate button on our account: https://gratipay.com/~riseup.net

I've added an email address, confirmed it and added a paypal connection, but it still isn't showing up.

The button I mean is like on this one, where it says "Give to Nuvola...": https://gratipay.com/nuvola-player/

Maybe we aren't "approved"? If so, how do we go about getting approved?

thanks!
Riseup

**Comment by whit537** [comment]
Sorry for the confusion, @riseupdotnet. :-(

When we relaunched as [Gratipay 2.0](https://medium.com/gratipay-blog/gratipay-2-0-2453d3c53077) earlier this year, we reified a distinction between so-called "~users" and "Teams." We have a ticket about better differentiating ~user and Team pages (#3852), and I've added a +1 for you there.

You can read our [2.0 announcement](https://medium.com/gratipay-blog/gratipay-2-0-2453d3c53077) for all the details, but the tl;dr is that you'll need to [apply for a new Team](https://gratipay.com/new) in order to get back on track.

**Comment by whit537** [comment]
Gonna go ahead and close this out. We can reopen if you have more questions here. :-)
