### ISSUE TITLE
Improve navigation to payment methods

### ISSUE THREAD

**Issue by rohitpaulk** [gratipay/gratipay.com#3906]
We seem to be leaking the `exchange_routes` terminology into our UI

<img width="230" alt="screen shot 2016-01-24 at 4 11 52 pm" src="https://cloud.githubusercontent.com/assets/3893573/12535810/ae5ad4a4-c2b5-11e5-9f10-c7868a9b8b7e.png">

It isn't obvious what the `Routes` tab will lead to. I think we should term this as `Payment Routes`/`Payment Methods` in the UI. 

<img width="617" alt="screen shot 2016-01-24 at 4 12 52 pm" src="https://cloud.githubusercontent.com/assets/3893573/12535813/d84fb8ba-c2b5-11e5-9721-ed6eafba5300.png">

For the tab though, we could use just 'Payments'

<img width="617" alt="screen shot 2016-01-24 at 4 13 24 pm" src="https://cloud.githubusercontent.com/assets/3893573/12535814/d9c363a4-c2b5-11e5-95bf-c8cd3c56ae66.png">

**Comment by techtonik** [comment]
I think that it is good that we're leaking it. =) It provides transparency to people on how the funding actually work. 

Sticking to `Payment` narrows Gratipay to being just accounting system. With Gratipay 1.0 `Routing` concept meant that people can reroute the donations to other people, and now they will be able transparent view on how money are moving, and how the routes are setup.

Yes, the UI is not there yet, because Gratipay 1.0 is shut, but I think that `Routing` is still more useful menu item than `Payments`. It you want to de-clutter interface, I would move `Emails` into `Settings`, renamed `History` into `Balance` (I believe @Changaco did that already) and moved that balance out of `Settings`.

**Comment by Changaco** [comment]
(I guess @techtonik is talking about https://github.com/liberapay/liberapay.com/issues/67, but it's only tangentially related to this ticket. Liberapay has a [`Money I/O` label](https://github.com/liberapay/liberapay.com/labels/Money%20I%2FO) for issues related to routes, but we don't have a Routes page, we have a Payin and a Payout page instead.)

**Comment by techtonik** [comment]
Yes, but this ticket is labelled `improve navigation`, so it is related to user experience when they need to find a way to what:
1. "add money to their account"
2. "need to pay"
3. "need to setup the source of payment"

**Comment by rohitpaulk** [comment]
> but this ticket is labelled improve navigation

Exactly, @techtonik. As a first-time user who isn't familiar with Gratipay terminology, would you expect the `Routes` tab to lead to any of the 3 options you mentioned above?

**Comment by aandis** [comment]
When I was working with #3887, it took me a while to understand that `Routes` actually means `Payment Routes`. If `Payments` doesn't exactly describe it, I think `Payment Routes` is a better option than just `Routes`. It at least makes it clear that it has something to do with payments.

**Comment by aandis** [comment]
That is the reason that I added `Payment Routes` instead of `Routes` in 86ca3d8cdec98c85ac0ba7189b271af9f487bfbd.

**Comment by whit537** [comment]
> It isn't obvious what the `Routes` tab will lead to. 

I agree that "Routes" is confusing to users (and I like "Money I/O" as a developer-facing term). I didn't go with "Payment Routes" originally because it was so long relative to the other nav items. "Payments" is maybe okay—probably better than "Routes"—though that's still ambiguous: is that payments I've made in the past? recurring payments I want to make in the future? oh, it's ... my bank account and credit card.

Looks like PayPal handles this with a "Money" page (which could start to move us towards #1063):

![screen shot 2016-01-24 at 9 43 20 pm](https://cloud.githubusercontent.com/assets/134455/12541330/d89d3d5a-c2e3-11e5-8d70-93379976e4e4.png)

![screen shot 2016-01-24 at 9 43 25 pm](https://cloud.githubusercontent.com/assets/134455/12541332/dc92ad46-c2e3-11e5-9609-1b8c3d8a19cc.png)

**Comment by whit537** [comment]
Not sure how deep we want to set the plow here, though. We could spend a lot of time and energy if we stir the pot on navigation and IA, and I think we have [bigger fish to fry](https://github.com/gratipay/inside.gratipay.com/issues/472#issuecomment-172504406). I'd accept a simple PR that changes "Routes" to "Payments" (or "Money").

**Comment by whit537** [comment]
+1 on [Twitter](https://twitter.com/JVimes/status/709574112121716736).
