### ISSUE TITLE
Re-add widget menu item

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#3924]
The widget menu item should be added back for ~~Teams only, not~~ for individual ~users.

(Change in direction at https://github.com/gratipay/gratipay.com/pull/4172).

------------

https://gratipay.com/about/me/widgets/ was removed when widgets broke after Gratipay 2.0.

Can be done after the [Widgets for Gratipay 2.0](https://github.com/gratipay/grtp.co/milestones/Widgets%20for%20Gratipay%202.0) milestone is closed.
##

**Comment by nobodxbodon** [comment]
Seems working for me:
![screen shot 2016-11-03 at 8 12 26 am](https://cloud.githubusercontent.com/assets/392497/19971801/5df5c7e0-a19d-11e6-93d9-6c84b9157e2b.png)
What's expected behavior?

**Comment by whit537** [comment]
Hmm ... I had forgotten that this page is still there, just not listed in nav! Good find. :-)

Are you clear on the distinction between Teams and ~users, @nobodxbodon? If not, let's get you clear on it, because it matters here.

> What's expected behavior?

I think we should remove the first "Button" section entirely. That really applies to Teams now, not to ~users. Same with "Badge."

I suppose we could keep the "Giving & Receiving Widgets," though now it should be "Giving & *Taking*" If the taking side is too broken, then we can at least document the giving side.

Thoughts, @nobodxbodon @mattbk?

**Comment by nobodxbodon** [comment]
@whit537 Here's what I understand about the concepts, teams and users. A user can sign up any time. A team needs to be approved. A user can have multiple teams. Givers can give to teams, not individual user. If a user is owner of the team, she can distribute the income as she likes. Please correct if any is wrong.

Sounds good to your expected behavior.

BTW, I see in [~whit537](https://gratipay.com/~whit537/) the bitcoin address, which should be removed, as Bitcoin was dropped per [previous discussion](https://github.com/gratipay/gratipay.com/issues/1451#issuecomment-147411970)?

**Comment by whit537** [comment]
> Here's what I understand about the concepts, teams and users.

👍

> Sounds good to your expected behavior.

👍

> bitcoin address, which should be removed

Can you reticket if we don't already have a ticket about this?

**Comment by nobodxbodon** [comment]
@mattbk could you check if this is solved already, with my latest commit?

**Comment by mattbk** [comment]
For reference: https://github.com/gratipay/gratipay.com/pull/4172

The page looks good. I think we're still half and half with the receiving vs taking terminology for ~users. Fixing that requires going back to https://github.com/gratipay/grtp.co.

The next step is to add the menu item back so people can see it.

**Comment by whit537** [comment]
>  I think we're still half and half with the receiving vs taking terminology for ~users. 

Say more? Are we going live with this—saying "taking"—without updating the widget to also say "taking" instead of "receiving"?

going live = linking in the nav

**Comment by mattbk** [comment]
Individual widgets should say taking, team widgets should say receiving. I need to refresh my memory and get back to this.

**Comment by mattbk** [comment]
> going live = linking in the nav

Let's go live with this for ~user pages with the current terminology for now.

We should add a link to https://github.com/gratipay/grtp.co, because that is where team widgets are explained and code given.

Additionally, we should add a menu link for logged-in team members on team pages, and have the team widgets available there.

**Comment by mattbk** [comment]
Working on this today. Undoing https://github.com/gratipay/gratipay.com/pull/3673.
