### ISSUE TITLE
Admins can't see team owner on team page when logged in

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#3945]
Logged out:
![image](https://cloud.githubusercontent.com/assets/3729038/13672887/4e1efb5a-e69c-11e5-9a19-f2ff317bb87a.png)

Logged in:
![image](https://cloud.githubusercontent.com/assets/3729038/13672878/42c8470c-e69c-11e5-8264-39b8cbb45aaa.png)

**Comment by aandis** [comment]
This was done in #3923, specifically [here]( https://github.com/gratipay/gratipay.com/commit/95be8d2ee73b22ed41ad40f1b091739f7145ad61#diff-54fc7e025b41a7185c3ff65e3111b6f8R112).
The idea was that for team owners, having an `owned by` isn't really necessary since they are well aware they own the team. But maybe it *is* necessary for admins. Do you something specific in mind about where to show it? Showing it beside those 5 options would look a bit clumsy imo.

**Comment by mattbk** [comment]
It's helpful for admins when reviewing teams, since we usually look up the owner and then tag them on GitHub. Since only admins would see it, I wouldn't have a problem putting it beside those existing options for now in order to get the functionality back.

Might relate to https://github.com/gratipay/gratipay.com/issues/3852.

**Comment by aandis** [comment]
Alright! :)
