### ISSUE TITLE
use two decimals in input in giving knob

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3966]
Raised [on Twitter](https://twitter.com/JVimes/status/709575233603182593) (cc: @JVimes). The issue is that we're using `format_decimal` there, and it doesn't know how to enforce two decimal places.

![mbt9kdlwda](https://cloud.githubusercontent.com/assets/134455/13766832/c3a44964-ea3b-11e5-80bd-13b5b0b3ce26.gif)

![h6cri0ct3m](https://cloud.githubusercontent.com/assets/134455/13766834/c5ad0db8-ea3b-11e5-85b8-47078947317f.gif)

I think there may be other places we're afflicted by this as well? Maybe re: widgets?

**Comment by whit537** [comment]
template: https://github.com/gratipay/gratipay.com/blob/1942/templates/your-payment.html#L22

`format_decimal`: https://github.com/gratipay/gratipay.com/blob/1942/gratipay/utils/i18n.py#L219 (delegated to `babel`)

**Comment by mattbk** [comment]
> Maybe re: widgets?

I think I solved this in https://github.com/gratipay/grtp.co/pull/118, but that's JS...

**Comment by aandis** [comment]
https://github.com/gratipay/gratipay.com/issues/3966

**Comment by etanol** [comment]
I've seen this issue linked from python-babel/babel#90.  You need to keep in mind that `format_currency` and `format_decimal` have different number patterns by default.  Since you can specify an explicit number pattern, my advice is to to the following:

1. Extract the default currency pattern of the locale in use
2. Remove the currency symbols from it: `¤`
3. Use the result as an explicit pattern to either `format_decimal` or `format_currency`
