### ISSUE TITLE
remove bitcoin part in "Other Giving Options" from user profile

### ISSUE THREAD

**Issue by nobodxbodon** [gratipay/gratipay.com#4174]
Discussed [here](https://github.com/gratipay/gratipay.com/issues/3924#issuecomment-258261908).

**Comment by whit537** [comment]
There are two other giving options, Bitcoin and Venmo. Are we talking about removing the whole section, or just the Bitcoin option?

**Comment by nobodxbodon** [comment]
I'm not sure about Venmo. Is it dropped as well?

**Comment by whit537** [comment]
The point of the section is to list other ways besides Gratipay to give. They're just links. Gratipay is not directly involved in the flow of funds for either of those methods.

**Comment by nobodxbodon** [comment]
Before I check the source code, I suppose users can add giving option by 
themselves. IIUC, Gratipay no longer allows giving Bitcoin, then we just 
need to remove the Bitcoin option in there?

**Comment by rohitpaulk** [comment]
I think we should either remove it, or move the whole section to Teams rather than users

**Comment by mattbk** [comment]
I vote to remove it. This sort of thing can be included in the ~user or team profile.

Having those fields seems like we're specifically endorsing those services and/or getting some part of the transaction, and neither is true.

Their also definitely not "other receiving options" because we don't pay out through them. 

Additionally (and finally), it's weird that they're listed under the "social profiles" section of the profile anyway.

**Comment by nobodxbodon** [comment]
I'll start to work on this, because it's apparently causing confusion like @tswast mentioned in https://github.com/gratipay/gratipay.com/issues/3627#issuecomment-245669617:
> I tried to apply for a new team and was confused as well, since I did not see PayPal listed as one of the account link options (Bitcoin and Venmo were there, though). I eventually found it through the "Routes" link, but I didn't know that was how to receive payment until I clicked through. Maybe "Payment Routes" isn't the clearest of terms.
