### ISSUE TITLE
Don't show "add email" notification while claiming package

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#4429]
It's distracting, because they are in the process of adding an email!

![screen shot 2017-04-27 at 3 09 27 pm](https://cloud.githubusercontent.com/assets/134455/25500107/b3276c44-2b5b-11e7-8486-2a9fb0fb19b4.png)

**Comment by whit537** [comment]
It's also on the verification success page?!

![screen shot 2017-04-27 at 3 16 54 pm](https://cloud.githubusercontent.com/assets/134455/25500326/9dd0e00e-2b5c-11e7-995b-58a9f5dcfbad.png)

**Comment by kaguillera** [comment]
I was working on this today... while trying to test it I had a thought. If I come to Gratipay for the first time and I log in using elsewhere (life github as I use) don't we want to show the notification even if the original reason that I came to the site was to claim a package. 
Because if I don't have an email how do we know that a package is associated to me? Unless that notification is still showing after and email has been verified...then that is an entirely different problem and not what I thought this issue is was about. Will continue on this tomorrow.

**Comment by whit537** [comment]
Per IRL convo, closing because we can't repro.
