### ISSUE TITLE
history does not show an external payout that happened

### ISSUE THREAD

**Issue by simonmichael** [gratipay/gratipay.com#4540]
https://gratipay.com/~simonmichael/history/ -> June 29, 2017 — Weekly Payday #265 shows no Outside activity, but I did receive $0.98 from gratipay to paypal on that day.

Related to #838.

**Comment by simonmichael** [comment]
(It is shown under July 6, 2017 — Weekly Payday #266 , but it happened on June 29).

**Comment by rohitpaulk** [comment]
Thanks for reporting, @simonmichael.

**Comment by rohitpaulk** [comment]
One of those was initiated by me (payday 266), the other (payday 265) by @whit537. Looks like this is due to https://github.com/gratipay/inside.gratipay.com/issues/1110#issuecomment-312103882. We had a bug that prevented us from being able to record paypal payouts in our database. It was fixed in the next week, and records added.

We could change the times on those records... Hmm, wonder if that would that mess with anything. I suppose we could try it out locally and run the 'check_accounts' cron to see.
