### ISSUE TITLE
allow for one-off tips

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#5]
The essence of Gittip is recurring tips, but once we solidify that I'm open to mixing in one-offs.

The reason recurring tips are important is because my mortgage is recurring and Gittip is about paying my mortgage.
##

**Comment by GBH** [comment]
So I have this open-source project. I'd like to bundle a 3rd-party software with it. License to do so costs X number of dollars. I would be awesome if I could collect that via Gratipay. Seems that's not really possible at the moment. So that's +1 from me.

Is there an alternative service I can use for this?

**Comment by techtonik** [comment]
> Is there an alternative service I can use for this?


It is a good idea to maintain a list of Gratipay alternatives, so that
people could choose the service that is closest to their goals and
audience. Listing open source and closed source, project based
(kickstarter, indiegogo), opaque but popular (paypal), Bitcoin based,
etc.

**Comment by rohitpaulk** [comment]
@techtonik, @GBH - http://inside.gratipay.com/appendices/see-also

**Comment by anselmh** [comment]
I’m not sure how much impact this would really have but I currently receive about $30 via GratiPay, mostly for one project, a weekly newsletter. Therefore the weekly billing is pretty much perfect for me.

Still I get a lot of emails and mentions asking why I don’t offer one time donations.
The reason is I don’t want to offer a PayPal button and besides that any other solution (I know of) would take too much of the share (10% + 30ct is ridiculous when we talk about $1-5 donations).

Therefore I think it would be great for people to being able to make a 1-time donation as well. It comes with the risk of not being able to calculate the revenue appropriately but it enables many more people to donate for what they love.

**Comment by navarr** [comment]
I think Gratipay has differentiated itself by now - it'd be really great to get one-time tips in there, as just an additional option on the payment page while the default focus remains weekly payments.

**Comment by waldyrious** [comment]
I've been thinking on and off about the different models followed by Gratipay, Flattr, Patreon, and others for quite a while. I finally decided to roll up my sleeves and try and get the distinctions cleared up by assembling an explicit and hopefully comprehensive framework of thought where these projects could fit and be compared to each other.

Please take a look at [this (in progress) document](https://docs.google.com/spreadsheets/d/1iSw6N9DhWMYIi8cphqoZqp0DkbK7R1g7vdA6b5yKNHs/edit#gid=0) and let me know if you have any feedback :)

**Comment by Maxhodges** [comment]
>Agree, let's ride the "weekly" wave for a while. We can reticket this if/when there is demand.

Clearly a very strong demand for one-time pay has been demonstrated in this thread. I think you're being a bit stubborn with your idealism. People want one-time option.

here is why I didn't use gittip even though I would like to tip several developers. If I setup $1 per week for several developers then my accounts payable staff needs to add a bunch of extra bookkeeping transactions each month into our accounting system also also they need to reconcile those transactions. So the cost of multiple, recurring tips is administratively high. Also the developers actually earn less, due to  per transaction fixed fees. Stripe fees are 2.9% + 30¢ per successful charge. So the developers would lose over 30% of the payment at $1 weekly compared to one-time fee of $25 or $50.

**Comment by Maxhodges** [comment]
this ticket is 3 years old ;) 

In theory I could just fork this project and add one-time payment right? it's public domain code?

**Comment by whit537** [comment]
Yes, you could fork. You could also give us a pull request. ;-)

**Comment by navarr** [comment]
@Maxhodges You'd probably want to give a PR - I mean, it has an $80 bounty on it ripe for the claiming.

**Comment by pluma** [comment]
Just for the tally: I'm withdrawing my +1 as I'm no longer interested in the project.

**Comment by tshepang** [comment]
I don't think anyone is keeping count, or at least not anymore, given the great desire for this feature.

**Comment by mattbk** [comment]
Would be cool if this could be integrated with GitHub, in order to donate after a PR rather than before (https://twitter.com/AntJanus/status/643207755814338561).

**Comment by kzisme** [comment]
@mattbk link broken

**Comment by mattbk** [comment]
+1 from https://botbot.me/freenode/gratipay/2015-09-21/?msg=50183992&page=1

**Comment by kzisme** [comment]
I know we are currently focusing on Payroll and other things, but are one-off donations still being thought about for the future?  

I ask because we had a recent inquiry about that feature on [Twitter](https://twitter.com/SimoEast/status/669328162166181888)

**Comment by mattbk** [comment]
I think it's still on the table, not sure where it fits on the roadmap.

**Comment by whit537** [comment]
Still on the table from my pov. I think, post-[2.0](https://medium.com/gratipay-blog/gratipay-2-0-2453d3c53077), that we should broaden our payments product to be more full-featured: one-off payments, as well as different recurring options.

**Comment by mattbk** [comment]
+1 from http://twitter.com/dchw/status/862681585157406720.

**Comment by whit537** [comment]
+1 from @HTCode in https://github.com/gratipay/gratipay.com/issues/4474.

**Comment by HTCode** [comment]
I think that after so many years, there is enough evidence that the one-off payments feature is useful. I hope that it will be considered soon. Is there any decision taken about this ?

**Comment by whit537** [comment]
We'll get to it eventually.

**Comment by whit537** [comment]
+1 from Danny Spitzberg in private email.

**Comment by mattbk** [comment]
+1 from https://gratipay.freshdesk.com/helpdesk/tickets/8688.

**Comment by whit537** [comment]
Calling this done in #4598. 😅

**Comment by helmo** [comment]
@whit537 please claim the $80 bounty for this on https://www.bountysource.com/issues/317079-allow-for-one-off-tips

**Comment by whit537** [comment]
Thank for posting the bounty so long ago, and for the gentle prodding now. However, we have decided that it's time to [close down Gratipay](https://gratipay.news/the-end-cbfba8f50981), and it wouldn't feel right to claim this bounty in light of that. 🙇

**Comment by helmo** [comment]
Thanks for trying all these years.

PS: I've mailed a request to bountysource to refund this bounty.

**Comment by Cervator** [comment]
Bounties refunded. Sorry to hear the bad news. Sincerely :-(
