### ISSUE TITLE
implement a basic income

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#84]
Make it possible to allocate a portion of one's weekly balance to a community chest, which would algorithmically be distributed amongst the community. What should the algorithm be?
- anyone can take up to $N.
- anyone can take any amount at any time
- taking is throttled according to karma (previous giving? previous receiving? throttled which way?)
##

**Comment by mattbk** [comment]
Reading this, I assume it is blocked because we couldn't verify that every account on Gratipay was owned by a (single) real person.  With teams under Gratipay 2.0, it seems that we are doing our identification due diligence ("community curation") before a person gets into the system, so maybe this is now possible?

**Comment by whit537** [comment]
@Sirjazzfeet points to http://groupincome.org/ (yes?) at https://www.loomio.org/d/tNhk36m9/group-income.

> Not sure if this runs into the same money transfer issues as before, but wonder if Gratipay has anything to learn from the idea:
>
**Clean and Simple** It's a mockup, but I like clean interface and simple functionality.
>
**Data Visualizations** Attractive graphs that make data easy to interpret.
>
**Transparency and Trust** Visibility of who the money is going to = trust.
>
**Democratic Distribution** Limits on income and equal distribution = trust.
>
**Group Basic Income** Attractive narrative with growing support.
>
![income](https://cloud.githubusercontent.com/assets/134455/11869578/eb1e46e0-a48e-11e5-8871-ec44bc68d073.png)

**Comment by Sirjazzfeet** [comment]
Naturally when people think of basic income a top-down approach comes to mind, as its ideally to everyone. But such top-down design is archaic and is increasingly being made to look very foolish. I'm all for a system that reaches to everyone, but how we reach that point is important, the means influence the ends. 

We need to move away from the totalitarian-like approach of enforcing universal re-distribution through centralised command design of economy and towards greater respect for cultural subjectivity, freedom and democracy. We should seek to maximise individual empowerment and reduce dependence on centralised power (not to say centralised power shouldn't help to resource and develop). The top-down approach will always prone to exploitation and lean towards criminality and greater violence to enforce. Information asymmetry between designers and users leads to makes it inefficient, inflexible, blind, politically abrasive, difficult to scale due to lack of critical distributed control, security and trust.

So an incremental bottom-up design, that will perhaps become federated, but certainly more organic, this would be easier to implement politically / culturally (the main obstacle) but also more resilient and dynamic, allowing for greater interoperability.. the potential for integration with social organisation, markets, commons, reputation systems, etc. A self-sustaining platform rather than a handout.     

Some ideas: 
[Taxemes](https://www.youtube.com/watch?v=QCpqFbA8wLc)
[Ecology Network](https://www.youtube.com/watch?v=8j9j6fLA6RI)
[Distribution Voltage](https://www.youtube.com/watch?v=cJXS0SoL0iA)
[Incentives](https://www.youtube.com/watch?v=Yo4Fs3nnA0U)
[Market Freedom](https://www.youtube.com/watch?v=lrnkg0jcQ0c)

**Comment by whit537** [comment]
> Resilience — a fully voluntary wealth sharing network

https://medium.com/@resilience_me/resilience-a-fully-voluntary-wealth-sharing-network-6873c927736a

**Comment by Sirjazzfeet** [comment]
"Community curation isn't sufficient for KYC (#3289)" 

What is KYC, how come team curation doesn't solve the issue?

**Comment by whit537** [comment]
KYC stands for "know your customer" and refers to the identity verification requirements of the global financial system. The tl;dr of #3289 is that we've got to collect national identity numbers and other personally identifying information, and cross-check it with screening vendors such as [Trulioo](https://www.trulioo.com/).

In Team curation we look at whether they provide open work and fit our brand, we don't do any identity verification there currently.

**Comment by Sirjazzfeet** [comment]
What I'm saying is: if a team made it transparent that once their basic income quota was full, any further donations for that month would go directly a person or team they have designated, does there still need to be KYC? after all a team wouldn't give money to someone they didn't trust or know.

( I must have been tired, could have google'd the definition also, sorry. )

**Comment by whit537** [comment]
> shouldn't the responsibility of distributing their basic income be with the team.

Huh. I've been thinking so far that basic income would attach to individuals, not to Teams. There'd be some pool that everyone on Gratipay could voluntarily pay in to, which would redistribute equally to every individual on the platform.

Let's say there are 10,000 users on Gratipay, and 1,000 pay in to the basic income pool totaling $1,000 per week. Everyone would get 10¢ of basic income per week, in addition to what they take for themselves from the Teams of which they're a member. Perhaps companies (including many Teams) could pay into the basic income pool as well, though they wouldn't receive basic income since it attaches only to natural persons.

How are you thinking basic income would work?

**Comment by mattbk** [comment]
> Let's say there are 10,000 users on Gratipay, and 1,000 pay in to the basic income pool totaling $1,000 per week. Everyone would get 10¢ of basic income per week

11 cents per week ($1,000/9,000 users), if you consider the silliness of giving out money for basic income and then receiving less of it right back.

**Comment by whit537** [comment]
Sure, though if we're talking silliness 11¢ a week doesn't go much farther than 10¢. :stuck_out_tongue_winking_eye:

**Comment by whit537** [comment]
Actually, I think this is an important question: who receives the basic income? Everyone? Or only the poor? If it's only the poor then it seems that we are reifying the distinction. Giving is empowering. If I'm poor enough to receive the basic income—what if I want to give 1¢ a week *into* the basic income pool? "Sorry, you're too poor to give." That doesn't seem right.

**Comment by Sirjazzfeet** [comment]
I'm thinking the group basic income would suit Gratipay best. Though you could have both if you like. But 10 cents is neither here nor there. With Group Basic Income, each group decides who their excess income goes to. Thereby creating an incentive to collaborate and focus resources towards commonwealth projects. Such a bottom up approach takes care of such questions, if people want to give to poor only, that's fine, but this way they are not forced to. But since groups set transparent caps on their income, distributing the overflow to form basic income network, it becomes exponentially inclusive.

**Comment by nobodxbodon** [comment]
Moved to https://github.com/gratipay/inside.gratipay.com/issues/973 for high-level discussion. Will reopen when there's concrete plan and design.
